### ISSUE TITLE
Pull requests to update registry

### ISSUE THREAD

**Issue by RP-OIS-SK** [OpenCerts/opencerts-website#105]
Hi,  I have put up a pull request to add an entry to registry for RP. I have yet to receive any reply for 3 days. Did I miss any step or any missing information for the pull request ?

**Comment by lanlan3322** [comment]
Same here for Institute of Blockchain.

**Comment by yehjxraymond** [comment]
We are in the midst of gathering info on how to verify the identity of the institutes. In the meanwhile please proceed to develop your custom certificate template (if any). The registry entry is not a prerequisite for rendering custom certificate templates.
