### ISSUE TITLE
Unable to view custom template - No Permission To Render Template

### ISSUE THREAD

**Issue by erwinsg** [OpenCerts/opencerts-website#114]
Hi Raymond, Rui Jie,

I am unable to view my custom template after latest code merging. As I need to deploy the template to UAT, appreciate if you could assist on this.

Thank you.

![image](https://user-images.githubusercontent.com/43283667/53922417-2a05fa00-40af-11e9-94cb-e2aeb05f8876.png)

**Comment by yehjxraymond** [comment]
Hi please check that your store address is in the list of whitelisted store address in the template files.

**Comment by erwinsg** [comment]
Hi Raymond,

Can please advise which files should I edit?
Previously, it works when we edit index.js, but after latest code sync, it does not work anymore.

const SEABCert = ({ certificate }) => (
  <MultiCertificateRenderer
    certificate={certificate}
    templates={templates}
    whitelist={approvedAddresses}
  />
);

**Comment by yehjxraymond** [comment]
The array of addresses going into the whitelist you wrote up there

**Comment by erwinsg** [comment]
ok, thank you.

We will create a pull request soon for your checking on the custom template.
