### ISSUE TITLE
Decoupling presentation layer from certification validation 

### ISSUE THREAD

**Issue by waichung** [OpenCerts/opencerts-website#118]
Current flow of open certs requires certificate to be validate before certificate will be rendered in it's visual form to the user. I suggest separating out the presentation view layer so it can be used on it's on. i.e. for the issuer to visually check the certificates before the hash is written to the blockchain.

**Comment by rjchow** [comment]
#112 might satisfy what you're looking for?
https://deploy-preview-112--opencerts-development.netlify.com/frameless_viewer/
it'll directly render the certificate text string that's placed into the text box

it's still a WIP but feedback is most certainly welcome

**Comment by waichung** [comment]
@rjchow Yes this fits my use case perfectly. May I know when will this be pushed to the master branch? Is opencerts intending to make it part of the entire opencerts repository or will you create a standalone utility out of it?

**Comment by rjchow** [comment]
It'll be part of the OpenCerts repository as we don't want to replicate the templates, and at the same time extracting the templates into its own package will prove challenging for the code-splitting that we've currently implemented

**Comment by waichung** [comment]
Thanks for your reply @rjchow. Please see my edited comment. Apologise for the inconvenience caused.

**Comment by waichung** [comment]
> @rjchow Unfortunately, after examining the feature more deeply, it does not fit my use case. Are there plans to roll out a feature that renders a certificate that has not be signed? i.e.
> 
> ```
> {
>   "id":"2018091259",
>   "name":"Bachelor of Blockchain",
>   "issuedOn":"2018-08-31T23:59:32+08:00",
>   "issuers":[{
>     "name":"University of Blockchain",
>     "url":"https://universityofblockchain.com",
>     "certificateStore":"0x1989a05B320186f5fAc590fFf64730FC9099Bc7b"
>   }],
>   "recipient":{
>     "name":"John Snow",
>     "email":"johnsnow@gmail.com",
>     "phone":"+6588888888"
>   },
>   "transcript":[{
>     "name":"History of Blockchain",
>     "grade":"B+",
>     "courseCredit":3,
>     "courseCode":"HIST-BTC",
>     "url":"https://universityofblockchain.com/sub/hist-btc",
>     "description":"Understanding the origins of the blockchain."
>   },{
>     "name":"Ethereum Smart Contracts",
>     "grade":"A",
>     "courseCredit":3,
>     "courseCode":"ETH-SC",
>     "url":"https://universityofblockchain.com/sub/eth-sc",
>     "description":"Understanding how to write smart contracts on the Ethereum network."
>   }],
>   "additionalData": {
>     "signature":"data:image/jpeg;base64...."
>   }
> }
> ```

Thanks for your reply @rjchow. Please see my edited comment. Apologise for the inconvenience caused.

**Comment by rjchow** [comment]
> @rjchow Unfortunately, after examining the feature more deeply, it does not fit my use case. Will there be concerns with the OpenCerts team to render a certificate that has not be signed? i.e.
> 
> ```
> {
>   "id":"2018091259",
>   "name":"Bachelor of Blockchain",
>   "issuedOn":"2018-08-31T23:59:32+08:00",
>   "issuers":[{
>     "name":"University of Blockchain",
>     "url":"https://universityofblockchain.com",
>     "certificateStore":"0x1989a05B320186f5fAc590fFf64730FC9099Bc7b"
>   }],
>   "recipient":{
>     "name":"John Snow",
>     "email":"johnsnow@gmail.com",
>     "phone":"+6588888888"
>   },
>   "transcript":[{
>     "name":"History of Blockchain",
>     "grade":"B+",
>     "courseCredit":3,
>     "courseCode":"HIST-BTC",
>     "url":"https://universityofblockchain.com/sub/hist-btc",
>     "description":"Understanding the origins of the blockchain."
>   },{
>     "name":"Ethereum Smart Contracts",
>     "grade":"A",
>     "courseCredit":3,
>     "courseCode":"ETH-SC",
>     "url":"https://universityofblockchain.com/sub/eth-sc",
>     "description":"Understanding how to write smart contracts on the Ethereum network."
>   }],
>   "additionalData": {
>     "signature":"data:image/jpeg;base64...."
>   }
> }
> ```

That'll be a no, as this feature is meant for embedded certificate rendering and we haven't anything in the pipeline that requires rendering unsigned certificates - perhaps you could just run it through the signing utility? There's no additional verification so it's just a data formatting issue

**Comment by waichung** [comment]
I see. Thanks for your reply. My use case requires frequent changes to the certificate data and rendering it before it is finally signed and committed to the blockchain. Hence, having a decoupled certificate rendering from verification would be best instead of having to regenerate the hashes every single time a change has been made. However, if it is not within the pipeline, I have no choice but to work around it. Appreciate your quick replies.

**Comment by waichung** [comment]
@rjchow May I know when will this feature likely be rolled out?

**Comment by wmclaxton** [comment]
I would like to contribute to this discussion.  A user-friendly issuance application will have a flow such as: import, generate, review, issue and verify in different phases.  After generating certs, we forsee a review phase before issuance in which the issuer's adminstrator may correct data (eg- fix spelling errors) or delete particular records from a batch.  This review would need to permit viewing of an unsigned cert, that is, one which passes JSON schema validation but has not yet been issued and has no merkle tree hash included.

What we are requesting is a separate entry point for viewing but without validation.  This addition will broaden the use cases for OpenCerts and help adoption.

**Comment by rjchow** [comment]
There's no validation on the frameless viewer, you will see that the following cert renders just fine 

As long as the data is in the right shape, it will work
Alternatively you can call the issueCertificate() method in @govtechsg/open-certificate on your unsigned data to get the "signed" certificate data, which will also render fine in the frameless viewer without any blockchain verification.

```
{
  "schema": "opencerts/v1.4",
  "data": {
    "id": "aaaaaaaa-aaaa-4aaa-aaaa-aaaaaaaaaaaa:string:2018091259",
    "name": "aaaaaaaa-aaaa-4aaa-aaaa-aaaaaaaaaaaa:string:Bachelor of Blockchain",
    "issuedOn": "aaaaaaaa-aaaa-4aaa-aaaa-aaaaaaaaaaaa:string:2018-08-31T23:59:32+08:00",
    "issuers": [
      {
        "name": "aaaaaaaa-aaaa-4aaa-aaaa-aaaaaaaaaaaa:string:University of Blockchain",
        "url": "aaaaaaaa-aaaa-4aaa-aaaa-aaaaaaaaaaaa:string:https://universityofblockchain.com",
        "certificateStore": "aaaaaaaa-aaaa-4aaa-aaaa-aaaaaaaaaaaa:string:0x1989a05B320186f5fAc590fFf64730FC9099Bc7b"
      }
    ],
    "recipient": {
      "name": "aaaaaaaa-aaaa-4aaa-aaaa-aaaaaaaaaaaa:string:John Snow",
      "email": "aaaaaaaa-aaaa-4aaa-aaaa-aaaaaaaaaaaa:string:johnsnow@gmail.com",
      "phone": "aaaaaaaa-aaaa-4aaa-aaaa-aaaaaaaaaaaa:string:+6588888888"
    },
    "transcript": [
      {
        "name": "aaaaaaaa-aaaa-4aaa-aaaa-aaaaaaaaaaaa:string:History of Blockchain",
        "grade": "aaaaaaaa-aaaa-4aaa-aaaa-aaaaaaaaaaaa:string:B+",
        "courseCredit": "aaaaaaaa-aaaa-4aaa-aaaa-aaaaaaaaaaaa:number:3",
        "courseCode": "aaaaaaaa-aaaa-4aaa-aaaa-aaaaaaaaaaaa:string:HIST-BTC",
        "url": "aaaaaaaa-aaaa-4aaa-aaaa-aaaaaaaaaaaa:string:https://universityofblockchain.com/sub/hist-btc",
        "description": "aaaaaaaa-aaaa-4aaa-aaaa-aaaaaaaaaaaa:string:Understanding the origins of the blockchain."
      },
      {
        "name": "aaaaaaaa-aaaa-4aaa-aaaa-aaaaaaaaaaaa:string:Ethereum Smart Contracts",
        "grade": "aaaaaaaa-aaaa-4aaa-aaaa-aaaaaaaaaaaa:string:A",
        "courseCredit": "aaaaaaaa-aaaa-4aaa-aaaa-aaaaaaaaaaaa:number:3",
        "courseCode": "aaaaaaaa-aaaa-4aaa-aaaa-aaaaaaaaaaaa:string:ETH-SC",
        "url": "aaaaaaaa-aaaa-4aaa-aaaa-aaaaaaaaaaaa:string:https://universityofblockchain.com/sub/eth-sc",
        "description": "aaaaaaaa-aaaa-4aaa-aaaa-aaaaaaaaaaaa:string:Understanding how to write smart contracts on the Ethereum network."
      }
    ],
    "additionalData": {
      "signature": "aaaaaaaa-aaaa-4aaa-aaaa-aaaaaaaaaaaa:string:data:image/jpeg;base64...."
    }
  },
  "privacy": {},
  "signature": {
    "type": "SHA3MerkleProof",
    "targetHash": "a",
    "proof": [],
    "merkleRoot": "a"
  }
}
```

**Comment by rjchow** [comment]
This feature has been merged into master

**Comment by waichung** [comment]
@rjchow thank you. I think that will do great.
