### ISSUE TITLE
SEO

### ISSUE THREAD

**Issue by yehjxraymond** [OpenCerts/opencerts-website#123]
See following reports:

[Web Page Analyzer Free Tool for SEO.pdf](https://github.com/OpenCerts/opencerts-website/files/2965598/Web.Page.Analyzer.Free.Tool.for.SEO.pdf)
[Seo-report.pdf](https://github.com/OpenCerts/opencerts-website/files/2965599/Seo-report.pdf)

**Comment by thefiend** [comment]
Fixed in #176 .
