### ISSUE TITLE
Bundle size optimisation

### ISSUE THREAD

**Issue by rjchow** [OpenCerts/opencerts-website#124]
web3 has a whole bunch of copies of BN.js

there's a solution here which works via webpack aliases
https://github.com/ethereum/web3.js/issues/1178#issuecomment-464648998

**Comment by jondavidjohn** [comment]
I built a tool to help you analyze webpack bundles for size regressions, and report them directly to GitHub PRs. It's free for open source, so it might be worth checking out and helpful in this scenario.

[https://packtracker.io](https://packtracker.io/?utm_campaign=links&utm_source=github&utm_medium=issueprcomment)

![image](https://user-images.githubusercontent.com/401520/58719965-8ae35c80-8396-11e9-908d-5c5b1d7b8cbf.png)

**Comment by rjchow** [comment]
that's really cool! thanks :)
