### ISSUE TITLE
Encountered error while npm installing packages, please see attached log 

### ISSUE THREAD

**Issue by leonglai59** [OpenCerts/opencerts-website#129]
Have installed the Git desktop for GitHub and clone the OpenCert repository into local GitHub\opencerts-website

However when running the npm install command from local GitHub\opencerts-website encounter the following error ;
C:\Users\S1343795E\Documents\GitHub\opencerts-website>npm install
npm WARN deprecated bfj-node4@5.3.1: Switch to the `bfj` package for fixes and new features!
npm WARN deprecated kleur@2.0.2: Please upgrade to kleur@3 or migrate to 'ansi-colors' if you prefer the old syntax. Visit <https://github.com/lukeed/kleur/releases/tag/v3.0.0\> for migration path(s).
npm WARN deprecated fs-promise@2.0.3: Use mz or fs-extra^3.0 with Promise Support
npm WARN deprecated tar.gz@1.0.7: ⚠️  WARNING ⚠️ tar.gz module has been deprecated and your application is vulnerable. Please use tar module instead: https://npmjs.com/tar
npm ERR! Error while executing:
npm ERR! C:\Program Files\Git\cmd\git.EXE ls-remote -h -t git://github.com/frozeman/WebSocket-Node.git
npm ERR!
npm ERR! fatal: unable to connect to github.com:
npm ERR! github.com[0: 52.74.223.119]: errno=No such file or directory
npm ERR! github.com[1: 13.229.188.59]: errno=No such file or directory
npm ERR! github.com[2: 13.250.177.223]: errno=No such file or directory
npm ERR!
npm ERR!
npm ERR! exited with error code: 128
[2019-03-22T02_16_37_805Z-debug.log](https://github.com/OpenCerts/opencerts-website/files/2995161/2019-03-22T02_16_37_805Z-debug.log)

**Comment by rjchow** [comment]
could be a firewall blocking git's ports
