### ISSUE TITLE
Deployment to Netlify failed 

### ISSUE THREAD

**Issue by ccewuz** [OpenCerts/opencerts-website#136]
Error observed is below. Any idea? Full log is attached.

5:12:47 PM: Error: Cannot find module '/opt/build/repo/node_modules/next/dist/bin/next-dev'
5:12:47 PM:     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
5:12:47 PM:     at Function.Module._load (internal/modules/cjs/loader.js:507:25)
5:12:47 PM:     at Function.Module.runMain (internal/modules/cjs/loader.js:742:12)
5:12:47 PM:     at startup (internal/bootstrap/node.js:282:19)
5:12:47 PM:     at bootstrapNodeJSCore (internal/bootstrap/node.js:743:3)

[netlify.log](https://github.com/OpenCerts/opencerts-website/files/3026482/netlify.log)

**Comment by yehjxraymond** [comment]
Is this from #135? Where do you get this error from?

**Comment by ccewuz** [comment]
yes, from #135. I was trying to deploy branch nus-templates with netlify which threw me this error.

**Comment by ccewuz** [comment]
settings:

repository: github.com/ccewuz/opencerts-website
build command: npm run dev
production branch: nus-templates

**Comment by yehjxraymond** [comment]
The setting should be:
Build Command: `npm run deploy`
Publish Dir: `out`

If you want to run on ropsten, set the env var:
NET=ropsten

**Comment by yehjxraymond** [comment]
But... why are you deploying your own copy? You can just use the PR copy...

**Comment by ccewuz** [comment]
It works. Thank you! I just want to do a quick test. The PR copy is not merged yet.
