### ISSUE TITLE
Opencert while loading encountered OpenCerts Privacy Filter Enabled

### ISSUE THREAD

**Issue by leonglai59** [OpenCerts/opencerts-website#156]
Hi,
    I am from ITE development team.
While loading the opencert for our template, we encountered OpenCerts Privacy Filter Enabled. 
unable to proceed to display our certificate.

Can you advise what must we do. Thanks.

![opencert_ite_issue2](https://user-images.githubusercontent.com/48785272/55764959-272c6980-5aa0-11e9-9e1a-bbaa37029e3b.JPG)

**Comment by rjchow** [comment]
You haven't pushed your commits to your repository on Github so I can't give a definitive answer, but I suspect one of the following:

1) you haven't set up the directory structure correctly with the template tags and exports
2) the $template tag in your certificate does not correspond to the one you have set up in the code repository

On the bright side, it looks like you've managed to issue the certificate correctly :-)

**Comment by yehjxraymond** [comment]
Closing issue, will wait for PR
