### ISSUE TITLE
Unable to run integration 

### ISSUE THREAD

**Issue by laykoonjune** [OpenCerts/opencerts-website#170]
Hi, 
I have install integration but initially it show that no test found but now it appear that it could not find integration. please advise. 

![image](https://user-images.githubusercontent.com/46921398/56272320-0f528680-612d-11e9-8a86-92bfb18e534b.png)
![image](https://user-images.githubusercontent.com/46921398/56272361-24c7b080-612d-11e9-9b64-5418af453580.png)
![image](https://user-images.githubusercontent.com/46921398/56272403-3610bd00-612d-11e9-9828-d4db88885fbc.png)
![image](https://user-images.githubusercontent.com/46921398/56272427-432dac00-612d-11e9-90a9-0cdceb2191ff.png)

**Comment by yehjxraymond** [comment]
There is no installation for integration test, please undo that global installation dont know what is that. 
Next, check that you are in the right folder, the package.json should have a integration script.

**Comment by laykoonjune** [comment]
I already run uninstall it. 
I am in the right folder with  package.json but seem like is it not picking up.

**Comment by laykoonjune** [comment]
I manage to run integration after updating package.json however it state testcafe is not recongise
![image](https://user-images.githubusercontent.com/46921398/56330191-92b9b980-61b9-11e9-94ee-975b07ea96f4.png)

**Comment by yehjxraymond** [comment]
have you ran `npm install`?

**Comment by yehjxraymond** [comment]
@rjchow also pointed that your code base may be too old. Could you check that you have pulled the latest code?

**Comment by laykoonjune** [comment]
I ran npm install before. I am able to run "npm run dev". 
Just pull the latest code but still getting the same error.

**Comment by yehjxraymond** [comment]
Please include the output from `git log`

**Comment by laykoonjune** [comment]
[2019-04-18T03_37_55_194Z-debug.log](https://github.com/OpenCerts/opencerts-website/files/3092937/2019-04-18T03_37_55_194Z-debug.log)

**Comment by yehjxraymond** [comment]
run `git log` and show the output from there.

**Comment by laykoonjune** [comment]
C:\Users\junel\Documents\Projects\OpenCerts\sourcecode\nyp_fork_copy\opencerts-website>git log
commit df772c167d43a8bed14c316258b34e258897d574 (HEAD -> master, origin/master, origin/HEAD)
Merge: fdba802 5b20ed9
Author: laykoonjune <june_lk_lim@nyp.edu.sg>
Date:   Thu Apr 18 11:32:27 2019 +0800

    Merge branch 'master' of https://github.com/OpenCerts/opencerts-website

commit 5b20ed9608bf5d628d20dc5b149cc65a0451280c (upstream/master)
Author: Wu Yong <36496605+mmysgp@users.noreply.github.com>
Date:   Thu Apr 18 10:04:48 2019 +0800

    fix certitifcate issuing date, full spelling of month (#172)

commit 225bd012b90d87e18889819057b30d14f1d88b34
Author: Wu Yong <36496605+mmysgp@users.noreply.github.com>
Date:   Wed Apr 17 14:10:54 2019 +0800

    [New Template] NP-AA1996-MAIN and include organization for CET transcript (#169)

    * NP: new template for 1996 FT Cert and include organization for CET transcript

commit fdba802e73e9ed233e8bd9111f02dafcb605542b
Author: laykoonjune <46921398+laykoonjune@users.noreply.github.com>
Date:   Tue Apr 16 16:45:33 2019 +0800

    Update registry.json

commit 864b988d8d6a4f82413294eaac990219555b7485
:...skipping...
commit df772c167d43a8bed14c316258b34e258897d574 (HEAD -> master, origin/master, origin/HEAD)
Merge: fdba802 5b20ed9
Author: laykoonjune <june_lk_lim@nyp.edu.sg>
Date:   Thu Apr 18 11:32:27 2019 +0800

    Merge branch 'master' of https://github.com/OpenCerts/opencerts-website

commit 5b20ed9608bf5d628d20dc5b149cc65a0451280c (upstream/master)
Author: Wu Yong <36496605+mmysgp@users.noreply.github.com>
Date:   Thu Apr 18 10:04:48 2019 +0800

    fix certitifcate issuing date, full spelling of month (#172)

commit 225bd012b90d87e18889819057b30d14f1d88b34
Author: Wu Yong <36496605+mmysgp@users.noreply.github.com>
Date:   Wed Apr 17 14:10:54 2019 +0800

    [New Template] NP-AA1996-MAIN and include organization for CET transcript (#169)

    * NP: new template for 1996 FT Cert and include organization for CET transcript

commit fdba802e73e9ed233e8bd9111f02dafcb605542b
Author: laykoonjune <46921398+laykoonjune@users.noreply.github.com>
Date:   Tue Apr 16 16:45:33 2019 +0800

    Update registry.json

commit 864b988d8d6a4f82413294eaac990219555b7485
Author: rjchow <me@rjchow.com>
Date:   Mon Apr 15 21:54:52 2019 +0800

    added fix for hyphens in domain names (#166)

    * added fix for hyphens in domain names

    * added header to legacy.js

commit 92e00d9f3dfc1b568e7ee8af94cb6a1e6a3340be
Author: yehjxraymond <yehjxraymond@gmail.com>
Date:   Fri Apr 12 16:00:19 2019 +0800

    Added ropsten emial api (#161)

:

**Comment by yehjxraymond** [comment]
could you run `npm i` one more time just to be sure that everything has been installed? It could be that npm dev works but integration test dont if the other dependencies werent installed.

**Comment by laykoonjune** [comment]
reinstalled and able to run. thanks.

**Comment by yehjxraymond** [comment]
np, closing isse.
