### ISSUE TITLE
Custom fonts in templates

### ISSUE THREAD

**Issue by ssgwsg-acn** [OpenCerts/opencerts-website#203]
Hi, We will need to use the Roboto font in our templates. Is it ok to add the Embed font link in the Meta.js file. I saw the other fonts like Source Sans Pro are included in the same file.

**Comment by rjchow** [comment]
open to trying, do it in your own templates and we'll have a look at the impact

**Comment by ssgwsg-acn** [comment]
We will use it in our templates. But want to know if we can include it in the src/components/Layout/Meta.js file?

**Comment by rjchow** [comment]
no you may not

**Comment by ssgwsg-acn** [comment]
Pls suggest how can we use custom fonts?

**Comment by rjchow** [comment]
https://developers.google.com/fonts/docs/getting_started

please do your own research on issues not particular to our codebase

**Comment by ssgwsg-acn** [comment]
What I want your input is if there is any specific folder/file you want us to include the font embed link in. We already know how to use include custom fonts. In fact, adding the font URL in the Meta.js file and using it our template is already working in our local. But you mentioned above that we cant change the Meta.js file. Hence the question.

**Comment by rjchow** [comment]
You can put it anywhere in your template, or if you would like to refactor your code to have a general container that's up to you too - as long as its inside ssg-wsg's folder and not loading for other templates
