### ISSUE TITLE
[Bug] Show correct feedback when certificate store not found at cert's indicated cert store

### ISSUE THREAD

**Issue by rjchow** [OpenCerts/opencerts-website#205]
currently we show a bunch of misleading errors, it should show an appropriate error message instead

**Comment by rjchow** [comment]
Design a priority order for the error messages so that they don't all show up, too

**Comment by rjchow** [comment]
We can detect the smart contract at an address using the following method:

```
> web3.eth.getCode("0xdcA6Eea7024151c270b50FcA9E67161119B06BAD").then((bc) => { return web3.utils.keccak256(bc) }).then(console.log)
Promise {
  <pending>,
  domain:
   Domain {
     domain: null,
     _events:
      [Object: null prototype] {
        removeListener: [Function: updateExceptionCapture],
        newListener: [Function: updateExceptionCapture],
        error: [Function: debugDomainError] },
     _eventsCount: 3,
     _maxListeners: undefined,
     members: [],
     [Symbol(kWeak)]: WeakReference {} } }
> 0x7135575eac76f1817c27b06c452bdc2b7e1b13240797415684e227def063a127
> web3.utils.soliditySha3(c.deployedBytecode)
'0x7135575eac76f1817c27b06c452bdc2b7e1b13240797415684e227def063a127'
```

A brief explanation:

Every smart contract on the Ethereum network is made up of a string of binary data, also known as the bytecode of the smart contract. This bytecode determines the behaviour of a smart contract, so you can say that if two contracts have the same bytecode they will have the same behaviour (i.e they are copies).

Each instance of the deployed DocumentStore is a smart contract and every version that we support has  bytecode associated with it.

Currently we only have one version (2.2.0) and the keccak256 calculated on its bytecode is '0x7135575eac76f1817c27b06c452bdc2b7e1b13240797415684e227def063a127'

If we can interrogate the bytecode at an address and calculate the keccak256 over it, and it results in the above string, then we can be confident that the smart contract at that address is a copy of our DocumentStore 2.2.0 smart contract.

Do also remember to account for the case where that is no smart contract at the address, please check what web3.eth.getCode returns for that case and handle it accordingly

**Comment by samuellye98** [comment]
#331
