### ISSUE TITLE
[Bug] Browser Back Button Issue

### ISSUE THREAD

**Issue by mmysgp** [OpenCerts/opencerts-website#270]
When user clicks on the browser "back"  button, an error message will be shown when they verify the same opencert.  I know that It's a common issue for web applications and the "back" button should not be clicked. But it's good to address it by showing some messages/instructions on the page. For consideration.

![browser-back-button-issue](https://user-images.githubusercontent.com/36496605/57670804-79365100-7643-11e9-8d72-b24fa98ae548.PNG)

**Comment by rjchow** [comment]
huh i don't think that's expected behavior, will look into it

**Comment by rjchow** [comment]
[Peek 2019-05-14 12-34.zip](https://github.com/OpenCerts/opencerts-website/files/3175847/Peek.2019-05-14.12-34.zip)

issue confirmed, video of how to reproduce it

**Comment by rjchow** [comment]
track progress in #275
