### ISSUE TITLE
Obfuscating data without enabling the obfuscation

### ISSUE THREAD

**Issue by sumitnitsurat** [OpenCerts/opencerts-website#280]
Without clicking on edit button click on  name, grade or course credit section. Its getting obfuscated.

**Comment by rjchow** [comment]
need more details

**Comment by sumitnitsurat** [comment]
Reproduce steps -

1. Go to https://dev.opencerts.io/
2. Take the default cert and drag to the dropzone.
3. Proceed to see the cert.
4. Now click on any course name, course code or grade. 

These values are getting obfuscated without even enabling the editing from the edit button.

**Comment by samuellye98** [comment]
https://github.com/OpenCerts/opencerts-website/pull/301
