### ISSUE TITLE
[BUG] Missing menu icon in mobile view

### ISSUE THREAD

**Issue by yehjxraymond** [OpenCerts/opencerts-website#289]
Introduced in #132 (74d93827e74ea44df38a4852617bdbfe97cef54d)

**Comment by sumitnitsurat** [comment]
I intentionally removed it.
1. We already have logo which points to home and Faq at the bottom. So I think its redundant to put a side bar for these 2 options.
2. We have another sidebar with different menu options while we go to the "/viewer". if we change the menu items only it may confuse users to the use of sidebar menu.
