### ISSUE TITLE
Certificates not valid after generation

### ISSUE THREAD

**Issue by RexShinka** [OpenCerts/opencerts-website#297]
Hi,
I am looking to propose this idea to Canadian Colleges. I have some contacts and experience with Ethereum. When I tried to generate certificates on my own store, I found the certificates were not valid. I worked on mainnet because I could not see how opecerts.io could switch to ropsten (for admin.opencerts.io, no problem). So I generated a store; 0xe9e3eAf8C47da2329748a889Fb5dc53066A4d499 and I put the store in the unsigned demo certs. I added the store address and text to the sample certificates;

{
"id":"2018091259",
"name":"Bachelor of Blockchain",
"issuedOn":"2018-08-01T00:00:00+08:00",
"issuers":[{
"name":"Rex Test School 1",
"certificateStore":"0xe9e3eAf8C47da2329748a889Fb5dc53066A4d499"
}],
"recipient":{
"name":"John Snow"
}
}

I installed the batch tool and ran the tool.

C:\Users\Rex\Documents\certs\certificate-cli>node index.js batch unsigned_certs signed_certs
2019-05-23T17:17:56.172Z info: Batch Certificate Root: 0x5c3e927b9a7c006b83cb0f96f3696c809311dc18cf702fa1da14ed9b8c7b4c60

The signed_cert directory was created and the signed cert was;

{
"schema": "opencerts/v1.5",
"data": {
"id": "7abcfe55-bf35-42cf-90d7-54e8567e5c19:string:2018091259",
"name": "a9d66b63-7d94-4496-9cb9-e9ca55c5c289:string:Bachelor of Blockchain",
"issuedOn": "f7215ff0-f2a2-49dd-9b6e-b433786c9f27:string:2018-08-01T00:00:00+08:00",
"issuers": [
{
"name": "7c0a1e4b-b5dd-4ce4-bd7f-9cddb30694e8:string:Rex Test School 1",
"certificateStore": "42995f2f-2f49-47c8-a9c3-802ea31387d0:string:0xe9e3eAf8C47da2329748a889Fb5dc53066A4d499"
}
],
"recipient": {
"name": "d3259410-c904-4ec9-b1bd-81836970af7e:string:John Snow"
}
},
"privacy": {},
"signature": {
"type": "SHA3MerkleProof",
"targetHash": "bdac32b313f0b5124583434dbda1cb57ef4ee8b214fd33a11f45fbe56cfbc23d",
"proof": [
"8f8e7033d82297c50298ba98220b6175e225d28b085907ea96f1055c788debe3"
],
"merkleRoot": "5c3e927b9a7c006b83cb0f96f3696c809311dc18cf702fa1da14ed9b8c7b4c60"
}
}

I issued the certificate batch using admin.opencerts.io.
Transaction id: 0xa858578a36a950b82b24f499d3865514d69d616a9d6fc1ea15924c38ede3df3a

I waited a bit to let the blocks propagate from Canada to Singapore and used opencerts.io to validate the certificate. It did not work. Obviously the school is not on the list but it was all red.

What did I miss?

P.S. The signed certs are not very human readable.

Also I would like an email to ask some other questions (less technical)

My email rex@ethereumusecases.com

**Comment by rjchow** [comment]
I pasted the cert contents that you provided into a .opencert file and it checks out fine on opencerts.io, not sure what's causing the issue you're facing?

![image](https://user-images.githubusercontent.com/27843274/58300795-9bd02300-7e16-11e9-8988-220b5e031f4f.png)

By the way you can use the ropsten viewer at https://dev.opencerts.io 
Are your other queries on business or technical issues? I can hook you up with our business folks if its the former, otherwise we can continue here no problem

**Comment by RexShinka** [comment]
Hi,

 

Sorry for the delay.

 

OK, I got it working.  Does the file type matter?

 

I will continue to play with it.  Out of curiosity, can only the account that creates a store add a hash to it?  If not that would be an attack vector.  

 

I will start to reach out to some of the Canadian colleges.  

If I contact someone and they want to email someone in the Singaporean school management, could I ask for an email I could forward?

 

Best Regards,

 

Rex Hygate

**Comment by rjchow** [comment]
The extension has to be .opencert , and yes only the owner of the DocumentStore smart contract can issue hashes on it.

I will put the business folks in touch with you via your email on your website
