### ISSUE TITLE
Question: On Viewer

### ISSUE THREAD

**Issue by ryansena** [OpenCerts/opencerts-website#298]
If the opencert file both contains certificate & transcript, is there any way for the students/alumni to  hide their transcript for viewing?

**Comment by rjchow** [comment]
https://docs.opencerts.io/appendix_data_obfuscation.html

**Comment by ryansena** [comment]
"For instance, a button can be created to hide the entire transcript or a delete button can be added to each field to remove only one value."

Kindly confirm my understanding:
So basically the student click the button to hide the transcript and download the new cert file?
The student will then now have 2 copies of the file and both of these files are still will be certified and not revoke the other one:
- 1 with both cert & transcript
- 1 with cert only

**Comment by rjchow** [comment]
yup exactly

**Comment by ryansena** [comment]
Thanks for the quick reply ;)
