### ISSUE TITLE
Unable to render custom template after rebasing

### ISSUE THREAD

**Issue by ccewuz** [OpenCerts/opencerts-website#335]
Hi, 

"yarn dev" shows the following warning

![image](https://user-images.githubusercontent.com/47135828/59339320-89227d00-8d36-11e9-81c9-222deb44292f.png)

Opening certificate on the browser shows the following

![image](https://user-images.githubusercontent.com/47135828/59339393-b0794a00-8d36-11e9-83d9-1aa5aa5d60b0.png)

All templates were working before rebasing my branch with the latest master.

Any advise?

Thanks,
Zehe

**Comment by yehjxraymond** [comment]
Hi after rebasing you will see that we have created an alias for the folder containing the MultiCertRenderer. You may reference code of the other certs to see the new path of the MCR

**Comment by ccewuz** [comment]
Hi, do you mean "template-utils/MultiCertificateRenderer"? I have changed this before rebasing. 

Also tried to re-code index.js to make it similar to other inst's templates, but error persists...

import { MultiCertificateRenderer } from "template-utils/MultiCertificateRenderer";
import { storeAddresses } from "../common";
import Degree from "./degree";

const templates = [
  {
    id: "degree",
    label: "NUS Degree",
    template: Degree
  }
];

const ANUNUSJDPBSOCSC2019 = () => (
  <MultiCertificateRenderer
    templates={templates}
    whitelist={storeAddresses}
  />
);

ANUNUSJDPBSOCSC2019.displayName = "ANU-NUSJDP-BSOCSC-2019 Degree Template";
export default ANUNUSJDPBSOCSC2019

**Comment by ccewuz** [comment]
ok solved. The curly braces must be removed.
