### ISSUE TITLE
Big changes in opencerts-website?

### ISSUE THREAD

**Issue by ccewuz** [OpenCerts/opencerts-website#360]
Hi, Just realized that there are some big changes in opencerts-website project folder. In particular, the whole "CertificateTemplates" folder is gone. Now where are templates stored and how can documents be rendered? Is there any channel from which we can be informed the latest changes? I subscribed to developer mailing list but never got anything...

**Comment by yehjxraymond** [comment]
Hey sorry we were just about to send an update on this. We have moved all templates to another repository: https://github.com/OpenCerts/legacy-templates.

This repository will only contain code for the main website. We are working on the documentation to allow schools to be able to create/edit templates without explicit approval from GovTech side.

**Comment by ccewuz** [comment]
Noted with thanks.
