### ISSUE TITLE
feat(verification): detect if certificate was issued after "valid until" date

### ISSUE THREAD

**Issue by rjchow** [OpenCerts/opencerts-website#368]
In our DocumentStore smart contract when we issue a merkleRoot, the value of the transaction block is stored. We also have a feature on the roadmap to allow issuers to declare that their DocumentStore is invalid after a certain block, say in the event of a key compromise.

We currently don't have the functionality on the site to store this "valid until" date, and we also don't check for this in the verification.

A successful implementation will have an integration test where

1. A cert is issued before a certain block and verification on this passes
2. A cert is issued after that block and verification on this cert should fail
3. A cert is revoked before a certain block and verification on this fails
4. A cert is revoked after that block and verification on this cert should pass

There should also be documentation for this contingency plan at docs.opencerts.io

**Comment by Nebulis** [comment]
We should support this at oa level, closing it for the time being
