### ISSUE TITLE
fix(viewer): numbers showing up above tabs

### ISSUE THREAD

**Issue by rjchow** [OpenCerts/opencerts-website#373]
![image](https://user-images.githubusercontent.com/27843274/61342519-07fe5e80-a87d-11e9-80aa-7ae46d56cdb0.png)

**Comment by samuellye98** [comment]
The latest changes in privacy.scss is overriding the global styles, instead we need to localise scss styles to its respective component.

**Comment by rjchow** [comment]
^ how does this work? i'm not familiar with css or scss but i dont see any global stuff in privacy.scss

**Comment by rjchow** [comment]
closed by #377
