### ISSUE TITLE
FAQ: Turn around time for merging to production

### ISSUE THREAD

**Issue by chongsoon** [OpenCerts/opencerts-website#380]
Hi,

I would like to find out to deploy to production, what is the turn around time?

In addition, the version of website I am working on has the templates folder, what would happen during the merge?

**Comment by yehjxraymond** [comment]
Depends on the code quality and size of commit. If there is nothing amiss and the number of files changed is not many, it will take a day or two. Do take note that the templates have been migrated to another repository https://github.com/OpenCerts/legacy-templates

**Comment by chongsoon** [comment]
I would like to find out how could we migrate over to legacy templates? Do we need to create another pull request? Thanks.

**Comment by rjchow** [comment]
yes please

**Comment by chongsoon** [comment]
I received the announcement regarding 2.0. If we are on 1.5, do we have to migrate to 2.0 and host our renderer in the future? In other words, does it mean all institutes need to migrate to 2.0 and host their renderer?

**Comment by rjchow** [comment]
if you're an SSG accredited institution (you are), you may continue submitting pull requests to our legacy renderer repo with the same workflow as previously up till the end of 2019
we will host the legacy renderer indefinitely so no worries about that.

beyond 2019, new templates will have to be self hosted by institutions
