### ISSUE TITLE
How to get pre v2.0 opencerts to render on opencerts.io?

### ISSUE THREAD

**Issue by waichung** [OpenCerts/opencerts-website#383]
With the introduction of DecentralisedTemplateRenderer, certificates that were issued in v1.5 and before cannot be independently verified, may I know is there a way to get the certificate template onto https://legacy.opencerts.io/? Maybe via a PR to https://github.com/OpenCerts/legacy-templates ?

**Comment by rjchow** [comment]
not sure I understand what you mean, what do you mean by independently verified?

**Comment by waichung** [comment]
Hi @rjchow. Thanks for replying. What I meant by independently verified is if I as a certificate holder wants to verify that the contents are real and use opencerts.io as a verification service. The question I'm asking is how to get certificates that were issued pre v2.0 to render on opencerts.io if the templates are not registered  https://github.com/OpenCerts/legacy-templates currently?

**Comment by yehjxraymond** [comment]
OpenCerts issued pre-2.0 were all on legacy templates repo. If they were not there they cannot be rendered. Two methods moving forward:
- If the issuing institute is part of those approved by SSG you may still submit new templates to legacy repo
- If the issuing institute is not part of that list, please use only v2 template

There should not be a case where it is issued (pre-2.0) but it’s template is not in the legacy repo.

**Comment by waichung** [comment]
Thanks for replying. We have a bunch of certificates currently issued in v1.5 format that points that uses the old method of certificate rendering. Is there a way to get on that repository and not have to reissue everything in v2.0?

**Comment by rjchow** [comment]
I don't quite understand which old method you're referring to if you didn't already have templates in the legacy folder?

**Comment by waichung** [comment]
Sure. I am clear now what your stance on this is. Cheers.
