### ISSUE TITLE
npm Install is failing 

### ISSUE THREAD

**Issue by sktumati** [OpenCerts/opencerts-website#385]
npm install --global --production windows-build-tools
Running with above command for Installing locally. Getting below error.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! windows-build-tools@5.2.2 postinstall: `node ./dist/index.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the windows-build-tools@5.2.2 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:

**Comment by rjchow** [comment]
we can't provide support for windows-build-tools, please see if you have followed their instructions correctly, otherwise create an issue on their issue tracker
