### ISSUE TITLE
fix(seo): broken links and missing sitemap.xml

### ISSUE THREAD

**Issue by thefiend** [OpenCerts/opencerts-website#397]
<img width="667" alt="Screenshot 2019-08-14 at 9 43 09 PM" src="https://user-images.githubusercontent.com/3714496/63025807-90077080-bedc-11e9-99a8-532d469b92ee.png">

https://www.brokenlinkcheck.com/broken-links.php#status

**Comment by thefiend** [comment]
Broken links fixed in #398 .

**Comment by thefiend** [comment]
Added sitemap.xml in #403 .

**Comment by Nebulis** [comment]
merged
