### ISSUE TITLE
How to use "UPORT-SIGNED" verification?

### ISSUE THREAD

**Issue by pranavburnwal** [OpenCerts/opencerts-website#404]
Hi Team,

As mentioned on 
https://github.com/OpenCerts/adr/blob/master/decentralized_identity_proof_DNS-TXT.md

How do we use "UPORT-SIGNED" Verification method? I was not able to find any docs on the same.  Can someone please point me in the right direction if it exists. If not please explain the steps required for doing this.

Thanks!

**Comment by rjchow** [comment]
Sorry Pranav, the documentation is misleading - those are examples of
future possibilities. Will amend the documentation to reflect that

**Comment by pranavburnwal** [comment]
All right. Thanks!
