### ISSUE TITLE
ask for certificateStore invalid

### ISSUE THREAD

**Issue by asepem7** [OpenCerts/opencerts-website#419]
Hi, how to make the valid certificateStore? i've already generate a sample certificate but after verify using opencerts, the certificateStore invalid. what should i do? should I need register first in collaborate?

I attach my sample certificate file

[4cccb403-bcf6-4bff-9f9d-33068f4901d5.zip](https://github.com/OpenCerts/opencerts-website/files/3619252/4cccb403-bcf6-4bff-9f9d-33068f4901d5.zip)

thanks

**Comment by yehjxraymond** [comment]
You deploy the contract store first before creating the file. See “deploying certificate store”

**Comment by asepem7** [comment]
{
  "schema": "opencerts/v2.0",
  "data": {
    "id": "baf84c09-8e5d-4bf8-ab56-ff693dae90fa:string:8",
    "description": "d4235246-6df6-48c8-ae71-d561d311a1d3:string:New test certification",
    "issuedOn": "ed79bed9-a68f-488a-b98f-64779a476bb1:string:2019-09-17T00:00:00.000Z",
    "expiresOn": "3d8d5751-29f0-42e9-94ce-5c0b68e2cebf:string:2022-09-17T00:00:00.000Z",
    "admissionDate": "26800965-11ff-4f51-a5a8-62f91fd8aa3a:string:2019-09-17T00:00:00.000Z",
    "graduationDate": "b509a006-7c06-420c-8f99-79a906ed87e5:string:2019-09-17T00:00:00.000Z",
    "cumulativeScore": "35c3c42e-b48a-4377-ab78-10933aceb368:number:90",
    "name": "e508151e-ac8e-4987-b001-141dba07de00:string:New Certificate",
    "recipient": {
      "name": "0c01630f-7c2e-467e-bbf0-53a4a985b415:string:First Recipient",
      "email": "ae6f14b4-6ebf-429d-b385-ef29db531742:string:first@recipient.com"
    },
    "issuers": [
      {
        "name": "0b65de00-13f0-4879-af6e-655a951e252e:string:STMIK New Doc Store",
        "url": "42b404dd-bcac-4fab-8c32-bedb97ba1f48:string:http://doc-store.ac.id",
        "email": "6c45ecb0-8aa0-4c5f-a826-0642fcb0f2e5:string:doc@store.ac.id",
        "certificateStore": "5f89f941-396b-402b-b3b8-096a58b8dc87:string:0x486a12A5D14Ca1D62f3d6797EF9dbeDF85d5729f"
      }
    ]
  },
  "privacy": {
    "obfuscatedData": []
  },
  "signature": {
    "type": "SHA3MerkleProof",
    "targetHash": "3b067806cc312d2b07696c71435d9e024716ef10a6c0000eb72047263fe8777e",
    "proof": [],
    "merkleRoot": "3b067806cc312d2b07696c71435d9e024716ef10a6c0000eb72047263fe8777e"
  }
}

I've follow step by step from docs but I've always get certificateStore invalid.
I've create the batch issue but the proof always empty array. what is wrong?

thanks

**Comment by rjchow** [comment]
0x486a12A5D14Ca1D62f3d6797EF9dbeDF85d5729f is on Ropsten (testnet), did you try on opencerts.io or dev.opencerts.io ? should use dev.opencerts.io for Ropsten cert stores

**Comment by asepem7** [comment]
this is my step 

1. Signed my certificate via the CLI
2. Issue cert via test ropsten
3. Use dev.opencerts.io to verify the cert
4. I got this following error: "Certificate store address is invalid"

the dev.opencerts.io is using ropsten too right?
I attach my file
[e981982f-a8d9-42f2-b43b-e525cbc4f2c3.zip](https://github.com/OpenCerts/opencerts-website/files/3791990/e981982f-a8d9-42f2-b43b-e525cbc4f2c3.zip)

**Comment by asepem7** [comment]
oops sorry I used solidity  v0.5.

but in this file I've change to solidity v0.4 but still same error
[test.zip](https://github.com/OpenCerts/opencerts-website/files/3792393/test.zip)

**Comment by rjchow** [comment]
For institutions not under SSG (you aren't), you'll need to set up a DNS-TXT record in order to link your smart contract to your domain name so that we can determine that it is a legitimate issuer
Can find out more about that here: https://docs.opencerts.io/dns_verification.html

**Comment by asepem7** [comment]
in the future I should add value format like this : 
"issuers": [
    {
        "network": "ETHEREUM",
        "documentStore": "0x9178F546D3FF57D7A6352bD61B80cCCD46199C2d",
        "identityProof": {
            "type": "DNS-TXT",
            "location": "openattestation.com"
        }
    }
]

can you explain it 
openatts net=ethereum netId=1 addr=0x9178F546D3FF57D7A6352bD61B80cCCD46199C2d

net value is ethereum, it static value ?
netId value is 1, it static value ?

Thanks

**Comment by rjchow** [comment]
net=ethereum is static
netId=1 is for mainnet, 3 for ropsten testnet
addr=0x is your document store address

location would be the location of the dns record

**Comment by asepem7** [comment]
what different between documentStore and certificateStore ?

**Comment by rjchow** [comment]
use documentStore , certificateStore is an older term we were using before

**Comment by asepem7** [comment]
ok, I should change certificateStore to documentStore right ?
I will try it
thanks

**Comment by asepem7** [comment]
Still error, I've config the dns also cert file
if I check the dns i've got this response

{"Status": 0,"TC": false,"RD": true,"RA": true,"AD": false,"CD": false,"Question":[ {"name": "issuer.hsa2019.com.","type": 16}],"Answer":[ {"name": "issuer.hsa2019.com.","type": 16,"TTL": 88,"data": "\"hsa2019 net=ethereum netId=3 addr=0x5f916DC71c980A18540fbC749fc5c8C82363A6fb\""}]}

can check ? thanks

[2a6dcc14-720f-4169-a1cd-522d3c917127.zip](https://github.com/OpenCerts/opencerts-website/files/3796653/2a6dcc14-720f-4169-a1cd-522d3c917127.zip)

**Comment by asepem7** [comment]
work now I think it's because propagation in my DNS.

Thanks

**Comment by rjchow** [comment]
it worked for you? the record should read
"openatts net=ethereum netId=3 addr=0x5f916DC71c980A18540fbC749fc5c8C82363A6fb"

**Comment by asepem7** [comment]
yes I've changed also

**Comment by asepem7** [comment]
how if in opencerts change the solidity version? we still verified?

**Comment by rjchow** [comment]
will not affect anything

**Comment by asepem7** [comment]
Okay noted thanks
