### ISSUE TITLE
Legacy Templates sg/gov/seab

### ISSUE THREAD

**Issue by seab-gov** [OpenCerts/opencerts-website#420]
Hi Team,

Is there any steps for our reference for us to do some changes on legacy templates (sg/gov/seab) ?

For now, we managed to clone 'opencerts-website' and 'legacy-templates'  projects to our local.

Thanks

**Comment by yehjxraymond** [comment]
Please see the README of the legacy website: https://github.com/OpenCerts/legacy-templates

**Comment by seab-gov** [comment]
Hi, why cannot access the URL. Blank page displayed. 
https://deploy-preview-30--vigilant-newton-0ec838.netlify.com/

**Comment by rjchow** [comment]
https://github.com/OpenCerts/legacy-templates#development

**Comment by seab-gov** [comment]
Previously, we can access development server after successfully deployed. End user will used this URL to verify the changes.
Eg URL: https://deploy-preview-292--opencerts-development.netlify.com/


Is there any way we can view template in development server like previously done ?

**Comment by seab-gov** [comment]
We noted that the changes have been committed to master, but user has not completed UAT yet.
Can we check whether our code changes are now in production (https://opencerts.io/) as well? 

Branch Name: esor_19092019

**Comment by rjchow** [comment]
It is in production.

**Comment by seab-gov** [comment]
Previously, you will commit to master only after we put a comment in the pull request "Please commit to master".

Can we know the new process?
We would need user to complete UAT first before checking in the code to production.

**Comment by rjchow** [comment]
There's no new or old process, I assumed that you wanted it to be merged
urgently since you specifically tagged me.

If your code is not ready to be merged please do not call for attention, we
will review code only when it has been cleared on your side - especially if
it's for minor styling changes
