### ISSUE TITLE
Not able to see the cert in dev.opencerts.io

### ISSUE THREAD

**Issue by sktumati** [OpenCerts/opencerts-website#431]
![image](https://user-images.githubusercontent.com/17443178/67464612-3bb80400-f676-11e9-9d0e-af6583981206.png)

**Comment by rjchow** [comment]
send cert please

**Comment by sktumati** [comment]
means json file...?

**Comment by rjchow** [comment]
yea

**Comment by sktumati** [comment]
Just following up is there any clue for this...

**Comment by Nebulis** [comment]
Opening [Chrome devtools](https://developers.google.com/web/tools/chrome-devtools) show:

![image](https://user-images.githubusercontent.com/503185/67538741-99019300-f712-11e9-973a-2d738bd5fb25.png)

By using debugger we can notice than the certificate provided to `renderTwoSignatures` is undefined, leading to the error

**Comment by sktumati** [comment]
Not able to see the data on the cert and nothing is displaying in the transcript tab. While moving one tab to another tab all are disappearing.

**Comment by sktumati** [comment]
![image](https://user-images.githubusercontent.com/17443178/67542659-5fd01f80-f720-11e9-893d-ccedbe0e49e1.png)
