### ISSUE TITLE
Certificate issuer identity invalid

### ISSUE THREAD

**Issue by SP-INDT-OpenCert** [OpenCerts/opencerts-website#436]
Hi,

I'm working for the version 2 template, and had done the following:
- Created the new template, put the store address in the template.
- published it in netlify
- Signed my certificate via the new CLI
- Issue cert via test ropstein
- Use dev.opencerts.io to view the cert
- I got this following error:
"Certificate issuer identity invalid"

Regards,
Ryan

**Comment by yehjxraymond** [comment]
Hi please attach your document here. Please Ensure you do not have sensitive info in that doc. You might want to check if you have added the dns entry also, highly suspect that you miss out on that.

**Comment by SP-INDT-OpenCert** [comment]
I didn't setup the DNS in Netlify as my understanding is that it's for custom domain only.
I don't have the custom domain yet.

See attached opencert file, all contents are just dummy data.

[Version2_DPFT.zip](https://github.com/OpenCerts/opencerts-website/files/3781926/Version2_DPFT.zip)

**Comment by yehjxraymond** [comment]
Yep the identity portion is missing. Please see this doc:

https://docs.opencerts.io/dns_verification.html

You will need to append the identity claim statement in the certificate:

```
"identityProof": {
            "type": "DNS-TXT",
            "location": "your-domain-here.com"
}
```

For test net you will need to add the following entry into your dns at your domain (in this case `your-domain-here.com`):

```
openatts net=ethereum netId=3 addr=0x9B12B5C3fdA927ba4e9E707e2BA0b8405cAFB394
```

**Comment by SP-INDT-OpenCert** [comment]
Sorry I'm confused, looking at the [sample ](https://github.com/OpenCerts/open-certificate/blob/master/schema/2.0/example.json)for Schema 2.0, the identity proof wasn't indicated.

The sample schema had this syntax:
"issuers": [
    {
      "name": "Blockchain Academy",
      "did": "DID:SG-UEN:U18274928E",
      "url": "https://blockchainacademy.com",
      "email": "registrar@blockchainacademy.com",
      "certificateStore": "0xd9580260be45c3c0c2fb259a82f219b513054012",
      "additionalProp": "0x0000000000000000000000000000000000000000000000000000000000000000"
    },

Should we overwrite this issuers' content or append the identity proof?

**Comment by yehjxraymond** [comment]
Ohh that sample is slightly outdated. We will fix it, thanks for pointing it out. It should be:
```
"issuers": [
{
"name": "Blockchain Academy",
"did": "DID:SG-UEN:U18274928E",
"url": "https://blockchainacademy.com",
"email": "registrar@blockchainacademy.com",
"certificateStore": "0xd9580260be45c3c0c2fb259a82f219b513054012",
"identityProof": {
            "type": "DNS-TXT",
            "location": "your-domain-here.com"
},
"additionalProp": "0x0000000000000000000000000000000000000000000000000000000000000000"
},
```

in this case.

**Comment by SP-INDT-OpenCert** [comment]
thanks for the quick answer, what about the dns settings?
I can't see the dns settings for the default domain, I think I have to purchase/setup a custom domain to apply the DNS settings, is this correct?

It's there any workaround just for testing?

**Comment by yehjxraymond** [comment]
You can use your org dns for that. Change the domain to your domain. 

There’s currently no workaround for identity proofs

**Comment by SP-INDT-OpenCert** [comment]
I think my question is more onto this flow, currently it's something like this:
Certificate --> URL (custom primary domain) --> URL (Netlify's default subdomain)

Can we point directly to Netlify instead?
Certificate --> URL (Netlify's default subdomain)

**Comment by SP-INDT-OpenCert** [comment]
Still the same identity error, let me know if I missed out anything in your instructions.
[Setup Template.docx](https://github.com/OpenCerts/opencerts-website/files/3800376/Setup.Template.docx)

**Comment by SP-INDT-OpenCert** [comment]
gentle reminder pls.

**Comment by yehjxraymond** [comment]
Apologies, missed this thread. Could you attach the opencerts file directly, we have trouble with ms word docs. 

1. **Do not use netlify url directly**. If they are no longer offering the service or for some reason you want to change provider you are locked in to them. Using your own cname allow you to pick the provider of your choice. 

2. From what I can see, there is a few problems with the DNS records:
- The TXT record should read "openatts net=ethereum netId=3 addr=0x9B12B5C3fdA927ba4e9E707e2BA0b8405cAFB394". It's missing the "openatts" infront. You can compare yours (https://dns.google.com/query?name=openatts.sp-indt-opencert.online&type=TXT&dnssec=true) and another example (https://dns.google.com/query?name=tradetrust.io&type=TXT&dnssec=true)
- The domain should be the exact one you are are using on the certificate. So in this case, your certificate file should have the location pointed to `openatts.sp-indt-opencert.online`. I'm guessing you want to use the root domain, so you will have to insert the record as TXT under `sp-indt-opencert.online` instead.

**Comment by yehjxraymond** [comment]
If that didnt resolve, please attach your opencerts file and I'll help take a look.

**Comment by SP-INDT-OpenCert** [comment]
Still got the same issue, see attached file for the cert file and steps taken.
Not sure if this caused the issue, but on the signed cert file, the proof is blank.

[Test5.zip](https://github.com/OpenCerts/opencerts-website/files/3806973/Test5.zip)

**Comment by yehjxraymond** [comment]
Hey no worries you got it working already. You are probably viewing it on the wrong site. Please drop the cert in dev.opencerts.io. Opencerts.io is connected to main net.

Also it seemed like the renderer is not present at `sp-indt-opencert.online` so the display is a 404 not found instead.

**Comment by SP-INDT-OpenCert** [comment]
That's weird the renderer is already uploaded in the repository and I had linked it in Netlify, please see attached screenshots.

[Error 404.docx](https://github.com/OpenCerts/opencerts-website/files/3807517/Error.404.docx)

**Comment by yehjxraymond** [comment]
You can add the screenshot here directly.

**Comment by yehjxraymond** [comment]
I'm getting this if i visit the url directly.

![image](https://user-images.githubusercontent.com/7406870/68195412-c6432080-fff1-11e9-9e4b-e55c089a5955.png)

**Comment by SP-INDT-OpenCert** [comment]
Page is accessible, it's just showing blank:

![image](https://user-images.githubusercontent.com/54525549/68197587-7c5c3980-fff5-11e9-8673-d3dbf2ec48c8.png)

**Comment by yehjxraymond** [comment]
Can you add the ss of your netlify config for domain here? and also your repo that it's deploying from?

**Comment by yehjxraymond** [comment]
Make sure you have:
1. https enabled on the domain.
2. `"url": "04237f08-cc27-48cb-911a-b8c65e237e42:string:sp-indt-opencert.online"` to change to `"url": "04237f08-cc27-48cb-911a-b8c65e237e42:string:https://sp-indt-opencert.online"` instead

**Comment by SP-INDT-OpenCert** [comment]
Domain Settings:
![image](https://user-images.githubusercontent.com/54525549/68198897-e4ac1a80-fff7-11e9-8176-76a9eac21451.png)

I'm deploying from these repo: 
https://github.com/SP-INDT-OpenCert/demo-opencerts-renderer

Yes, https is enabled, I can already access the site here: https://sp-indt-opencert.online
Already modified the cert to use "https"
[Test5.zip](https://github.com/OpenCerts/opencerts-website/files/3808423/Test5.zip)

The invalid identity came back:
![image](https://user-images.githubusercontent.com/54525549/68199483-15d91a80-fff9-11e9-9bbf-0f82d7daaef5.png)

**Comment by SP-INDT-OpenCert** [comment]
Here's a copy of the certs with 404 and invalid identity error, with the only difference is on the url value
[Certs.zip](https://github.com/OpenCerts/opencerts-website/files/3812016/Certs.zip)

HTTPS was already enabled during the setup:
![image](https://user-images.githubusercontent.com/54525549/68259805-d997cf80-0075-11ea-8866-8804a5e17970.png)

**Comment by yehjxraymond** [comment]
https://dns.google/resolve?name=https://sp-indt-opencert.online&type=TXT

You can see that the TXT record cannot be found at the `dns` location. You will have to add https at the template url but at the identityproof there is no https since it's a dns record (not using http)

Try removing the https on the identityproof and you should be good to go.

**Comment by SP-INDT-OpenCert** [comment]
Thanks a lot for the help, everything seems to be working now.

**Comment by gjj** [comment]
Hey! I'm facing the same issue right now, though a [DNS lookup](https://dns.google/resolve?name=helloholo.sg&type=TXT) shows that I do have the `TXT` record with my document store.

```
{"name": "helloholo.sg.","type": 16,"TTL": 299,"data": "\"openatts net=ethereum netId=3 0x019d771a710ae45548ca5978f277633b25d4d2df\""}
```

Here's a snippet of my certificate prior to issuing.

```
{
	"id": "d58f0963-ce84-4b3e-95bb-e71aee953df5",
	"name": "Mixed Reality Developer Course",
	"issuedOn": "2020-12-31T23:59:32+08:00",
	"$template": {
		"name": "HELLOHOLO",
		"type": "EMBEDDED_RENDERER",
		"url": "https://renderer.opencerts.helloholo.sg/"
	},
	"issuers": [{
		"network": "ETHEREUM",
		"name": "HelloHolo",
		"url": "https://helloholo.sg/",
		"documentStore": "0x019d771a710ae45548ca5978f277633b25d4d2df",
		"identityProof": {
			"type": "DNS-TXT",
			"location": "helloholo.sg"
		}
	}],

        ... (removed for brevity)
}
```

I did the same steps described by OP (creating a cert using the npm package, then issuing the cert on Ropsten) in the first post and got the same `Certificate issuer identity invalid` error when verifying my signed certificate on https://dev.opencert.io

Not sure what am I missing out though.

**Comment by gjj** [comment]
Hey! I'm facing the same issue right now, though a [DNS lookup](https://dns.google/resolve?name=helloholo.sg&type=TXT) shows that I do have the `TXT` record with my document store.

```
{"name": "helloholo.sg.","type": 16,"TTL": 299,"data": "\"openatts net=ethereum netId=3 0x019d771a710ae45548ca5978f277633b25d4d2df\""}
```

Here's a snippet of my certificate prior to issuing.

```
{
	"id": "d58f0963-ce84-4b3e-95bb-e71aee953df5",
	"name": "Mixed Reality Developer Course",
	"issuedOn": "2019-12-31T23:59:32+08:00",
	"$template": {
		"name": "HELLOHOLO",
		"type": "EMBEDDED_RENDERER",
		"url": "https://renderer.opencerts.helloholo.sg/"
	},
	"issuers": [{
		"network": "ETHEREUM",
		"name": "HelloHolo",
		"url": "https://helloholo.sg/",
		"documentStore": "0x019d771a710ae45548ca5978f277633b25d4d2df",
		"identityProof": {
			"type": "DNS-TXT",
			"location": "helloholo.sg"
		}
	}],

        ... (removed for brevity)
}
```

I did the same steps described by OP (creating a cert using the npm package, then issuing the cert on Ropsten) in the first post and got the same `Certificate issuer identity invalid` error when verifying my signed certificate on https://dev.opencert.io

Not sure what am I missing out though.

**Comment by Nebulis** [comment]
Please open a new issue
