### ISSUE TITLE
Update to regsitry.json

### ISSUE THREAD

**Issue by ccewuz** [OpenCerts/opencerts-website#439]
Hi, We have realized that on /registry, NUS' info hasn't been added on. Can you help us update registry.json with the following info? Or shall we need to create a pull request? Thanks

{
    "0x51964385265eff73875a226aBf6fa20b0aAE4a6f": {
      "name": "National University of Singapore",
      "displayCard": true,
      "website": "https://www.nus.edu.sg/",
      "email": "transcript@nus.edu.sg",
      "phone": "+65 6516 2304",
      "logo": "/static/images/NUS_logo.png",
      "id": "nus-registry"
}

**Comment by rjchow** [comment]
will prefer you create a PR, thanks

**Comment by ccewuz** [comment]
A PR has been created. FYIA.

**Comment by ccewuz** [comment]
any update?

**Comment by Nebulis** [comment]
Sorry missed that one, I left a comment to clean package-lock.json

**Comment by Nebulis** [comment]
done
