### ISSUE TITLE
Certificate store address is invalid

### ISSUE THREAD

**Issue by ygengygeng** [OpenCerts/opencerts-website#448]
@rjchow @yehjxraymond 
Hi we are experiencing the following error when trying to validate on https://dev.opencerts.io/

"Please check that you have a valid smart contract with us and a correct certificate store address before proceeding."

We have asked the training provider (NIEC) to set up and deploy a certificate store (ropsten) and they have also submitted the following form https://form.gov.sg/5cd5141c02d207001007e322
The opencert file contains the certificate store which was passed to us.

May I check is the error an expected behaviour? Or are there more things that we need to do? Thanks!

**Comment by Nebulis** [comment]
Hi,

Could you provide us the certificate ?

**Comment by ygengygeng** [comment]
Hi Nebulis

[S80XXXXXJ_Aca.zip](https://github.com/OpenCerts/opencerts-website/files/3856341/S80XXXXXJ_Aca.zip)

**Comment by ygengygeng** [comment]
Hi @Nebulis 
Please help to check, Thank you!

**Comment by Nebulis** [comment]
Hi,

I noticed you sent a request to be added into the certificate registry, however SSG hasn't come back to us to approve your request. This explain the error you receive.

In the event SSG reject your request, you will have to use [DNS-TXT record](https://docs.opencerts.io/announcements/schema2_update.html).

I also noticed that you are missing the template property in your document, is it intended ?

**Comment by ygengygeng** [comment]
@Nebulis 
Thanks for the reply. We have not included the template as of now. Just curious, what happens if there is no template appended to the e-cert?

**Comment by Nebulis** [comment]
I guess nothing interesting as it's only used to display the certificate and not used in the process to verify the certificate. I will try later and see

**Comment by Nebulis** [comment]
So it defaults to the renderer for legacy certificates (pre v2) => https://legacy.opencerts.io/ and uses the defaults renderer that we created there

![image](https://user-images.githubusercontent.com/503185/69136883-a97d1180-0af6-11ea-8f62-257634c8f458.png)

I will close the issue as I think the initial topic is covered, feel free to open another issue if you need more help
