### ISSUE TITLE
Identity Registry

### ISSUE THREAD

**Issue by SP-INDT-OpenCert** [OpenCerts/opencerts-website#452]
Hi,

We just issued sample certs (schema 2.0) it looks ok except for the Skills Future portion:
 ![image](https://user-images.githubusercontent.com/54525549/69699277-76ec9d80-1122-11ea-98ca-6881afa05be8.png)

Do I still need to update the [registry](https://opencerts.io/static/registry.json) to include SP, eventhough we didn't get the "Certificate from unregistered institution" error?

**Comment by Nebulis** [comment]
Hi,

You need to fill a form to SSG to get approval to be added in the registry. If you already have the approval, you need to open a merge request to add your information in the registry.

**Comment by SP-INDT-OpenCert** [comment]
Thanks, we already finished on-boarding process with SSG earlier this year. Will just do a PR to update the registry.

**Comment by SP-INDT-OpenCert** [comment]
Created a PR, please help to check, thanks!
https://github.com/OpenCerts/opencerts-website/pull/453

**Comment by SP-INDT-OpenCert** [comment]
Gentle reminder pls.

**Comment by Nebulis** [comment]
Sorry for the delay, I dropped a comment, just need to resolve conflict and I merge right awayt

**Comment by SP-INDT-OpenCert** [comment]
Conflict resolved, please check.

**Comment by Nebulis** [comment]
merged
