### ISSUE TITLE
Update to NUS cert store

### ISSUE THREAD

**Issue by ccewuz** [OpenCerts/opencerts-website#458]
Hi, Sorry to disturb you again. Just created a PR to update cert store for NUS in registry.json. Can you please expedite the merge as we are going to issue certificates in these few days.

Thanks,

**Comment by Nebulis** [comment]
Did you send the change to ssg ? Could you provide them the new store address if you didn't have communicated yet?

**Comment by ccewuz** [comment]
[NUS Restricted]

Yes, we have informed SSG separately.

Thanks & Regards,
Zehe

**Comment by Nebulis** [comment]
Merged
