### ISSUE TITLE
Uncaught SyntaxError: Unexpected token '<' in new remote renderer

### ISSUE THREAD

**Issue by nikhilranosys** [OpenCerts/opencerts-website#459]
I was using old remote renderer format and every thing was working perfactly fine. Now after I upgraded to the latest format of remote renderer my templates are working fine when I test with storybook but when I tried to test it with local deployment of opencerts website I started getting below error in console when I upload certificate to verify.

**Error image 1**
![error1](https://user-images.githubusercontent.com/38653988/70139635-e3364680-16b8-11ea-8ca5-36bea6681c46.png)

**Error image 2**
![error2](https://user-images.githubusercontent.com/38653988/70139636-e3cedd00-16b8-11ea-8e8d-1da00f556bba.png)

**Comment by Nebulis** [comment]
Hi,

Do you have a certs so that we can test ?

**Comment by nikhilranosys** [comment]
remote renderer is on my local so you won't be able to test certs.

**Comment by Nebulis** [comment]
Then we can't help, the error is from the renderer

- Make sure the address you provided in the cert is loadable (i.e. copy the url in the browser and check what's happening)

**Comment by nikhilranosys** [comment]
When I opened it in the browser it was showing same error in console. I deployed my remote renderer using `npm run build` command, so thought of trying with `npm run dev` command and access remote renderer from dev port 3010 and it was working there perfactly.

So the summary is:

- When I build using `npm run build` command and deploy I got this error
- When I ruing using `npm run dev` command and access remote renderer from port 3010 it works fine

**Note:** I am using windows environment.

**Comment by Nebulis** [comment]
If we can't see the code or the build then we can't help

**Comment by Nebulis** [comment]
If we can't see the code or the build then we can't help

**Comment by nikhilranosys** [comment]
I can understand your point. I have check at my end in more detail and below is my findings.

When I deploy application on root address like `http://localhost:8081` etc then remote renderer works fine but if I deploy it in a sub folder like `http://localhost:8080/remote-renderer` then it gives me error.

Before this remote renderer upgrade I was using an attribute called `homepage` in my package.json to define my application subfolder URL but this don't work anymore in latest remote renderer.

Please suggested if there is any way to run remote renderer in sub folder.

**Comment by Nebulis** [comment]
Did you update the certificate `$template.url` to `http://localhost:8080/remote-renderer` ?

**Comment by nikhilranosys** [comment]
Yes

**Comment by Nebulis** [comment]
If you want further help you will have to provide code example to reproduce the problem. Per say I dont see any reasons for opencerts to not be able to load from a subfolder.

With information you provided, my understanding is that something is wrong somewhere in renderer configuration and we can't help if you don't provide anything

**Comment by nikhilranosys** [comment]
Here is my fork repository branch where I have implemented my templates
https://github.com/nikhilranosys/demo-opencerts-renderer/tree/smu-templates-new

**Comment by Nebulis** [comment]
Do you have a certificate to test with ?

**Comment by Nebulis** [comment]
- Do you have a certificate to test with ?
- How do you start the application that is built ?

**Comment by nikhilranosys** [comment]
1. Here is the test certificate. [11.txt](https://github.com/OpenCerts/opencerts-website/files/3926189/11.txt)

2. I have deployed built application on IIS.

**Comment by Nebulis** [comment]
what happens if you directly access to the URL deployed in your IIS ?

**Comment by nikhilranosys** [comment]
Yes, when I open this folder URL in browser it shows me same error

![image](https://user-images.githubusercontent.com/38653988/70225768-aaa87280-1775-11ea-8e6e-16b4bf2d93fb.png)

![image](https://user-images.githubusercontent.com/38653988/70225871-df1c2e80-1775-11ea-882c-b9f659c9ef08.png)

**Comment by Nebulis** [comment]
This confirms the error is from the renderer

If you deployed the same build on the root and on a subfolder, and if the error only shows up in the subfolder this means to me the issue is related to IIS and we definitely can't help you on this

**Comment by Nebulis** [comment]
1. I forgot that you need to specify a property in webpack to make it usable for subfolder => https://github.com/webpack/docs/wiki/configuration#outputpublicpath

2. The error that you show is weird, it looks like the bundle is not correct, maybe 1. will fix everything

**Comment by Nebulis** [comment]
Problem fixed ?
