### ISSUE TITLE
Second tab not showing on mobile browsers

### ISSUE THREAD

**Issue by ccewuz** [OpenCerts/opencerts-website#466]
Clicking on 2nd tab (Transcript) on mobile browser (Chrome & FF) does not show second page. I remember it worked before.

![image](https://user-images.githubusercontent.com/47135828/70872549-ea782100-1fe3-11ea-9e3d-20dd0278f8dd.png)

**Comment by Nebulis** [comment]
Indeed thx for the report

**Comment by Nebulis** [comment]
should be ok :ok_hand:
