### ISSUE TITLE
Request to change NUS logo

### ISSUE THREAD

**Issue by ccewuz** [OpenCerts/opencerts-website#469]
Hi, May I know what needs to be done if we wish to change the logo for NUS? 

Currently, NUS logo is https://opencerts.io/static/images/NUS_logo.png which is reflected on the following pages:

https://opencerts.io/
https://opencerts.io/registry

Since it is low-res and blurry, we wish to replace it with a new one in SVG format. May I know whether the following steps are correct for the change?

1) Delete static/images/NUS_logo.png
2) Add static/images/NUS_logo.svg
3) Amend static/registry.json, change the path to the logo accordingly
4) Create a PR

Thanks!

**Comment by rjchow** [comment]
correct! probably do a find and replace on the filename too just to be sure

**Comment by ccewuz** [comment]
Thanks. Found one more at src/constants/PartnerLogo.json

**Comment by ccewuz** [comment]
Created a PR. Please help with the merge.
