### ISSUE TITLE
CLI Tool

### ISSUE THREAD

**Issue by ygengygeng** [OpenCerts/opencerts-website#481]
@rjchow @Nebulis 
Due to requirements, we would like to check for the following regarding creation of merkle root hash: 

Instead of using directory path as input argument, does CLI Tool has a function to accept multiple-json format or base64-encoded-multiple-json as arguments for signing multiple certs?

Thank you

**Comment by Nebulis** [comment]
Hi,

It doesn't, could you give me context to understand what you are trying to achieve ?

**Comment by ygengygeng** [comment]
Hi @Nebulis 
We are trying to avoid writing/reading files to/from disk as the application that we are creating might have restricted read/write permissions depending on the environment.

**Comment by Nebulis** [comment]
In that case event the output will be an issue right ? The CLI currently output all files to a folder

**Comment by ygengygeng** [comment]
Yes. In the local testing environment, it would be ok.

**Comment by Nebulis** [comment]
We dont have plan to build such a thing yet, so if you need it you will have to make a MR or to write another cli

**Comment by ygengygeng** [comment]
Ok I will close the ticket for now
