### ISSUE TITLE
Another certificate issuer identity invalid issue

### ISSUE THREAD

**Issue by gjj** [OpenCerts/opencerts-website#485]
Hello! I'm facing a similar issue to #436, though a [DNS lookup](https://dns.google/resolve?name=helloholo.sg&type=TXT) shows that I do have the `TXT` record with my document store.

```
{"name": "helloholo.sg.","type": 16,"TTL": 299,"data": "\"openatts net=ethereum netId=3 0x019d771a710ae45548ca5978f277633b25d4d2df\""}
```

Here's a snippet of my certificate prior to issuing.

```
{
	"id": "d58f0963-ce84-4b3e-95bb-e71aee953df5",
	"name": "Mixed Reality Developer Course",
	"issuedOn": "2019-12-31T23:59:32+08:00",
	"$template": {
		"name": "HELLOHOLO",
		"type": "EMBEDDED_RENDERER",
		"url": "https://renderer.opencerts.helloholo.sg/"
	},
	"issuers": [{
		"network": "ETHEREUM",
		"name": "HelloHolo",
		"url": "https://helloholo.sg/",
		"documentStore": "0x019d771a710ae45548ca5978f277633b25d4d2df",
		"identityProof": {
			"type": "DNS-TXT",
			"location": "helloholo.sg"
		}
	}],

        ... (removed for brevity)
}
```

I did the same steps described by OP (creating a cert using the npm package, then issuing the cert on admin.opencerts.io using the `merkelRoot` to the Ropsten network) in the first post and got the same `Certificate issuer identity invalid` error when verifying my signed certificate on https://dev.opencert.io.

I've attached the signed file [here](https://github.com/OpenCerts/opencerts-website/files/4239575/test_cert.txt) that has been [issued](https://ropsten.etherscan.io/tx/0x126378d9609d74a5ac1b53aafe336e2eec1e13dac678af82ffc2d7cfe0776288) already. Not sure what am I missing out though.

**Comment by Nebulis** [comment]
https://docs.opencerts.io/dns_verification.html#create-dns-txt-record

your DNS record is not valid, you forgot addr in fron tof the address

**Comment by gjj** [comment]
Oh wow thank you for pointing it out! Must have accidentally replaced the `addr` when I copy pasted my address. It's working now!
