### ISSUE TITLE
Schema 2.0 / DNS TXT verification

### ISSUE THREAD

**Issue by XS-DT** [OpenCerts/opencerts-website#491]
Hi

There was previously a link to https://docs.opencerts.io/announcements/schema2_update.html but is now invalid and returns "Page Not Found" error. May I check what is the updated link?

How to implement DNS TXT verification?

**Comment by yehjxraymond** [comment]
Hi you can check out this guide: https://openattestation.com/docs/verifiable-document/dns-proof

**Comment by Nebulis** [comment]
On a side note, we have updated the doc on opencerts.io, I will probably add sth to help search in the documentation ( and eventually redirect to open attestation doc when needed) in the coming days
