### ISSUE TITLE
Enquiry

### ISSUE THREAD

**Issue by NIECOpencerts** [OpenCerts/opencerts-website#492]
Hi,

There are a few things that we would like to find out,

**1. Documentation for Opencert Scheme 2.0**
Previously we are given a link but is inaccessible now https://docs.opencerts.io/announcements/schema2_update.html

**2. Open Certs updated Developers guide**
We would also like to find out where can we download or view the latest developers' guide for OpenCert.

**3. View of Certificate template and Transcript in open cert**
We understand that there is this capability to view the actual certificate template and transcripts in open cert. We would also like to find out where can we find the developer guide, the documentation, and help on setting up to have this feature. Is there step by steps guide on how to set up the templates?

**4. Foreign IDs**
We noted that student will use SingPass to login. However, some foreign students do not have SingPass. What would be the advice and the steps for the foreign student to login to OpenCerts?

**Comment by Nebulis** [comment]
Hi,

1) I haven't ported back details on the schema v2 toi the new documentation but I could do it. What are you looking for:
- migration guide from v1
- détails on v2

2) and 3) docs.opencerts.io (and openattestation.com for the renderer)

4) no singpass for opencerts
