### ISSUE TITLE
Ethereum amount

### ISSUE THREAD

**Issue by NIECOpencerts** [OpenCerts/opencerts-website#493]
May we seek advice on the following:

1)	How much Ethereum amount will be deducted for one transaction of e-certificate uploading to OpenCerts?
2)	If the uploading of e-transcript to OpenCerts belongs to the same student as 1) above, will there be Ethereum deduction for the transaction?

**Comment by Nebulis** [comment]
We usually use 50 cents (SGD) per transaction as a reference. (just to help people having an order of price).

You can check the price directly on etherscan with certificate used by other:
- registry: https://opencerts.io/static/registry.json
- document store of one of the registry: https://etherscan.io/address/0xa5d801265D29A6F1015a641BfC0e39Ee3dA2AC76
- click on the latest transaction for that registry: https://etherscan.io/tx/0xba72190b214cf9a0ddec932a28e58ff4d520eec41e742f8cf5ea72972bf53685
- this one shows 18 cents (USD)

Don't forget that one transaction IS NOT one document, but a batch of document => you batch many document with the CLI, then issue ONE merkle root which means one transaction. You can batch all the certificates together or batch per multiple group, it's up to you (your strategy)

I'm not sure I understood your second question. Let me know if my answer didn't help

**Comment by NIECOpencerts** [comment]
Thanks for the explanation.

In that case, how many certificates can we batch together, i.e. is there a limit to the batch quantity?

**Comment by Nebulis** [comment]
There are no limits, you may face only physical limit (memory)

**Comment by NIECOpencerts** [comment]
Our vendor is enquiring for documentation on where to look out for the functionality to batch many document with the CLI, then issue one merkle root which means one transaction.

Will you be able to provide us that? Thank you.

**Comment by Nebulis** [comment]
You probably use https://github.com/OpenCerts/certificate-cli so documentation is in the readme

I recommend to use https://github.com/Open-Attestation/open-attestation-cli

Documentation is also in readme and a guide https://docs.opencerts.io/docs/transcripts

**Comment by NIECOpencerts** [comment]
Hi,

We would like to know more about the hosting of certificates / transcripts template. Have read and gone through the above link, they are all very technical. If as a institute staff with little IT knowledge, can you explain or is there any links for us to follow:
1. How to step the templates
2. where should these template be stored
3. from the technical side, they have to embed the URL to get the template, so where and how to host these templates. are they any guides on this.
4. As a staff if there is change of template fields, does it impact on those certs or transcripts that had  already been approved.

thank you.

**Comment by Nebulis** [comment]
You should find most of answers by following this guide https://openattestation.com/docs/verifiable-document/overview

**Comment by NIECOpencerts** [comment]
Got it! thanks!
