### ISSUE TITLE
Open-Attestation CLI

### ISSUE THREAD

**Issue by XS-DT** [OpenCerts/opencerts-website#496]
Hi
I was trying out V1.5 of Open-Attestation CLI and noticed that it added 
"version": "open-attestation/2.0" as one of the json property

The issue is that "version" is not recognised by SkillsFuture. They are still using "schema".

Which version of Open-attestation CLI should I use in this case so that it will produce "schema":"open-attestation/2.0"?

**Comment by XS-DT** [comment]
or can I continue to use the deprecated OpenCerts CLI v3.3.3?
it seems to be able to handle documentStore and identityProof as well as the the new $template.

**Comment by XS-DT** [comment]
Hi

Any advice for this? Thank you.

**Comment by XS-DT** [comment]
Any reply please ??

**Comment by Nebulis** [comment]
OOps missed that :grimacing: 

You need to use the --schema properties => [see the doc](https://docs.opencerts.io/docs/transcripts)

It will add the following to your file: `"schema": "opencerts/v2.0"`

Note the value of schema is the value of the $id property in https://schema.opencerts.io/transcripts/2.0 and the value is not correct it should be https://schema.opencerts.io/transcripts/2.0/index.json

Are you aware of any problem if we were to change from `"schema": "opencerts/v2.0"` to `"schema": "https://schema.opencerts.io/transcripts/2.0/index.json"`
