### ISSUE TITLE
Verification of OpenCerts failed before they enentually showed success

### ISSUE THREAD

**Issue by ccewuz** [OpenCerts/opencerts-website#518]
Hi, We have received some learners' feedback that when they dragged and dropped certs issued to them into opencerts.io, they saw errors like below.

![image](https://user-images.githubusercontent.com/47135828/86549330-ead10d00-bf71-11ea-8120-58cc3de13778.png)

But after a few times of re-trying, they were able to see the certs have been verified and the rendered contents.

May I know what is the reason ?

Thanks,
Zehe

**Comment by rjchow** [comment]
There was a temporary outage of our Ethereum API between 7pm to 9:30pm Sunday, apologise for the inconvenience
We will take measures to present a more accurate error message for future outages

**Comment by ccewuz** [comment]
I see. Thank you for your prompt response. I will close it.
