### ISSUE TITLE
Iframe update Height

### ISSUE THREAD

**Issue by asepem7** [OpenCerts/opencerts-website#525]
Hi,

How do I update iframe height when verify is successful and bring up the template in my URL? I have used penpal js for communication, and if I look at the method available on this website's opencerts which is updateHeight but when I call that method it doesn't work. what is missing from this

thanks

**Comment by Nebulis** [comment]
Hi,

that's the correct method to call as explained here (https://github.com/Open-Attestation/adr/blob/master/decentralised_rendering.md)

> Note that I'm not sure which version you use, but even if the ADR has been update to have a single API exposed, there are still function like `renderDocument` or `updateHeight`

We use that library that abstract this out (https://github.com/Open-Attestation/decentralized-renderer-react-components).

Do you have code that I could look at ? Or could you create a repo that reproduces the issue ?

**Comment by asepem7** [comment]
I have a page and on that page I call the function for updateHeight on the iframe opencerts website, but as if I can't connect to the iframe.

here is my code snippet:

`
const connection = Penpal.connectToParent();
connection.promise.then((parent) => {
// i try to set the static value
parent.dispatch('UPDATE_HEIGHT', 1000);
})
`

thanks

**Comment by Nebulis** [comment]
try the following:
```
const connection = Penpal.connectToParent(); connection.promise.then((parent) => { // i try to set the static value parent.dispatch({type: 'UPDATE_HEIGHT', payload: 1000}); })
```

Any reason you dont use our react templates (other than you dont use react) ?

**Comment by asepem7** [comment]
I still can't update the height even though I already followed the function. 

the reason is that we already have a different template and usage. I just need to display the page that I created to display it on the website opencerts. When I read the github, all I do is call the updateHeight method. So is there a way for me to make the page rendered through the url template display properly on the website opencerts besides I have to use the template provided?
or maybe we must add something in my function above?

Thanks

**Comment by Nebulis** [comment]
There is no need to use out template, it's just more convenient.

```javascript
parent.dispatch({type: 'UPDATE_HEIGHT', payload: 1000})
```
or
```javascript
parent.updateHeight(1000)
```

should work.

If both does not work, I will need to get more code than what you provided (you can set up a simple renderer with the minimal code to have it running and testing, for instance just use a template that display directly the content of the file provided)

**Comment by asepem7** [comment]
I have run both but it still doesn't work.

ok, I will create a minimal code by tomorrow.

Thanks

**Comment by asepem7** [comment]
Hi, I attach example code in html
index2.html is a frame to load my page (index.html)

[test.zip](https://github.com/OpenCerts/opencerts-website/files/4916140/test.zip)

thanks

**Comment by Nebulis** [comment]
Hi,

Before I dig, I notice you use the latest version of penpal (v5) and that we got troubles having v5 to v4 connection (I didn't investigate)

For instance we had to fix the penpal version in one of our repo (https://github.com/OpenCerts/legacy-templates/commit/69ca4027dab540e820a4e3c77e8a963a0b975d05)

**Comment by Nebulis** [comment]
I've changed to `https://unpkg.com/penpal@4.1.1/dist/penpal.min.js` and `parent.updateHeight(getDocHeight());` works

(dispatch doesn't work because we kep the other method for backward compatibility)

**Comment by asepem7** [comment]
yes it work for me too

thanks

**Comment by Nebulis** [comment]
According to v5 release:
```
This need has been raised several times in the past and was a fairly common use case. While this was not a breaking change, it did require significant changes to the handshake process as described in #32 (comment) and due to the higher risk of the change I decided to include it with other breaking changes in v5 rather than adding it to v4.
```

Hum ... :)

**Comment by asepem7** [comment]
hmm. okay thanks for info, i will take a note
