### ISSUE TITLE
Certificate Custom Template - Schema v1.5 and v2.0

### ISSUE THREAD

**Issue by seab-gov** [OpenCerts/opencerts-website#547]
Hi,

Currently, all the certificates issued are using schema 1.5 (for year 2020 and before).
From 2021, we will be using schema 2.0.
Can I check whether there will be issue if one organization using more than 1 schema for different issuing year?
Is there a lot of code change in the custom template program for upgrading from 1.5 to 2.0?

**Comment by Nebulis** [comment]
Please check https://docs.opencerts.io/docs/migrations/v1_to_v2 and let me know if you still have questions.

`Can I check whether there will be issue if one organization using more than 1 schema for different issuing year` => No problems
