### ISSUE TITLE
Print button on opencerts.io is not working.

### ISSUE THREAD

**Issue by opencert-sutd** [OpenCerts/opencerts-website#557]
Print button on opencerts.io does not work and hence the certs can't be printed. Please help.

**Comment by Nebulis** [comment]
Hi, Like I said the problem is probably with your renderer (the demo works fine), We will need more information about how you created the renderer

**Comment by opencert-sutd** [comment]
Hi, We rendered the documents from demo opencert document renderer on github.  To give more details on the issue, when we click on the Print button, nothing happens. Print wizard also does not pop up.
![Print_Cert_issue](https://user-images.githubusercontent.com/52150238/95535292-a6df1f80-0a1a-11eb-8eed-8c57eb31ccdd.JPG)

**Comment by Nebulis** [comment]
So you started from https://github.com/OpenCerts/demo-opencerts-renderer ? What's the version of govtechsg/decentralized-renderer-react-components in package.json ?

**Comment by opencert-sutd** [comment]
Hi, yes we forked the demo-opencerts-renderer in our account. I could not find this navigation : govtechsg/decentralized-renderer-react-components. Can you please confirm how I can check its version?

**Comment by Nebulis** [comment]
It looks like this https://github.com/OpenCerts/demo-opencerts-renderer/blob/master/package.json#L10, if you don't have it, then you probably forked the repository a long time ago and you have a file like this one https://github.com/OpenCerts/demo-opencerts-renderer/blob/067cc15e665aff7b6b9eb75a87f79e90365892db/src/components/documentViewer/documentViewerContainer.js

In the event you don't have govtechsg/decentralized-renderer-react-components, you can
1. upgrade to using this library (check the demo renderer)
1. handle print yourself:
	- create a print function https://github.com/OpenCerts/demo-opencerts-renderer/blob/067cc15e665aff7b6b9eb75a87f79e90365892db/src/components/documentViewer/documentViewerContainer.js#L78 : `const print = () => window.print()`
	- provide print to the frame https://github.com/OpenCerts/demo-opencerts-renderer/blob/067cc15e665aff7b6b9eb75a87f79e90365892db/src/components/documentViewer/documentViewerContainer.js#L86 :  
		```
		const parentFrameConnection = connectToParent({
        	methods: {
          		renderDocument,
				print,
		        selectTemplateTab
        	}
      	}).promise;
		```

**Comment by opencert-sutd** [comment]
Hi, 

Noted. Can you please share the steps for solution 1 :

**Comment by Nebulis** [comment]
I wrote this [tutorial](https://docs.opencerts.io/docs/migrations/migrate_renderer) to help user to migrate from the legacy renderer to the template we provide.

It might be slightly different but general steps are the same. It's a bit of work but the idea of the template is to abstract all the communication logic from you, so that you focus only on the template

**Comment by opencert-sutd** [comment]
Hi 
Just tried the solution 2 
Still I am not able to print. 
![image](https://user-images.githubusercontent.com/52150238/105813890-7af8a180-5feb-11eb-90e3-589f9252da76.png)
![image](https://user-images.githubusercontent.com/52150238/105814082-c90da500-5feb-11eb-9232-bd6c6bc33c12.png)

**Comment by Nebulis** [comment]
no idea what your code is doing or what you expect ir to do, but print is invoked through postmessage. If you dont provide more details that a screenshot of one line of code + it still doesn't work, I will not be able to help. Provides:
- code to your renderer OR
- reproduction repo 

As long as the demo works AND you can't provide information on your renderer, then it will be considered a bug on your renderer
