### ISSUE TITLE
Birthdate value not appearing correctly on opencerts.io

### ISSUE THREAD

**Issue by opencert-sutd** [OpenCerts/opencerts-website#570]
For one of the students, the birthdate on Opencerts.io is not appearing same as the value in the json file.
For eg : if the value is 3 Oct 19XX in the json file, it is appearing as 2 Oct 19XX.  For other students, the birthdate is correct.

**Comment by Nebulis** [comment]
Opencerts is not responsible for displaying the content of certificate, the renderer is. You should check with the people responsible of the renderer used to display the content.

It looks like a timezone issue
