### ISSUE TITLE
Could not issue OpenCerts for testing (Metamask)

### ISSUE THREAD

**Issue by yvonneyong** [OpenCerts/opencerts-website#573]
We encountered an issue where there was no response when trying to issue a test batch of OpenCerts.

<img width="506" alt="20201030" src="https://user-images.githubusercontent.com/50482118/97654257-7e889500-1a9d-11eb-81c0-6f8034b94b70.png">

**Comment by Nebulis** [comment]
Please paste your document store address

**Comment by yvonneyong** [comment]
0xb3c1404732585ddEB837Af28eBdAec504ed8Ba04

**Comment by Nebulis** [comment]
Thanks, if you open the developer console, do you see errors ?

**Comment by yvonneyong** [comment]
What are the steps to do this? I would need to communicate to the Registrar user who encountered it.

**Comment by Nebulis** [comment]
For chrome: https://developers.google.com/web/tools/chrome-devtools/open#:~:text=Press%20Command%20%2B%20Option%20%2B%20J%20(,Get%20Started%20With%20The%20Console.

Usually F12 is good enough

**Comment by yvonneyong** [comment]
![errors1](https://user-images.githubusercontent.com/50482118/97668393-d256a680-1abc-11eb-9ef5-c6597d0b01a4.png)
<img width="839" alt="errors2" src="https://user-images.githubusercontent.com/50482118/97668398-d5519700-1abc-11eb-8e8c-cb3f8cc660bd.png">

**Comment by Nebulis** [comment]
I tried and it works correctly. I received another report about a problem with using a ledger through metamask, is it the same person that reported the problem ?

**Comment by yvonneyong** [comment]
Yes, we only have 1 user does the OpenCerts issuance for Ledger and Metamask.
For this issue, she was only using Metamask, the Ledger was not connected.

**Comment by Nebulis** [comment]
So for the issue above, the person didn't use Ledger right

**Comment by yvonneyong** [comment]
Yes, she is doing UAT for a new OpenCerts template, so the Ledger was not used.

**Comment by Nebulis** [comment]
What's the version of chrome and metamask ?

**Comment by yvonneyong** [comment]
<img width="782" alt="Chrome" src="https://user-images.githubusercontent.com/50482118/97842900-60cc6180-1d23-11eb-89e1-07e02d44d148.png">
<img width="275" alt="Metamask" src="https://user-images.githubusercontent.com/50482118/97842905-645fe880-1d23-11eb-890c-9a9be7f495dd.png">

**Comment by Nebulis** [comment]
Everything is up to date. Is it possible to have a video to see what's happening ? (Maybe the person that face the issue can directly reply to my questions)

**Comment by yvonneyong** [comment]
Could we arrange an MS Teams session for you to see the issue?
I have done so with her and basically, when she tries to issue the OpenCerts, the Metamask wallet prompts to confirm the test ether spend. After she clicks on Confirm, nothing happens. The transaction confirmation didn't appear on the OpenCerts admin page.

**Comment by Nebulis** [comment]
Can you first provide me the metamask wallet address involved?

Otherwise can do this afternoon

**Comment by yvonneyong** [comment]
I just found out she's on leave today. Can we arrange for 3.30pm tomorrow?

**Comment by Nebulis** [comment]
Sure

**Comment by yvonneyong** [comment]
Thanks! Please share contact so we can include in the meeting invite.

**Comment by Nebulis** [comment]
maillet_laurent@tech.gov.sg

**Comment by Nebulis** [comment]
@yvonneyong please provide me the wallet address

**Comment by Nebulis** [comment]
@yvonneyong I will close this issue, feel free to re-open / re-contact me in case of troubles
