### ISSUE TITLE
Url to whitelist

### ISSUE THREAD

**Issue by CITAcadAppsSupport** [OpenCerts/opencerts-website#597]
Hi, 

can i have all the website list for whitelist on my UAT and Production server?

we have done whitelist for below url : 
-https://www.opencerts.io/*

but still not able to access some urls, please refer attached image.
![01](https://user-images.githubusercontent.com/50308837/107909668-a7bd2a80-6f93-11eb-9774-31fda517c188.png)

Thanks for your time.

**Comment by Nebulis** [comment]
As shown in your image, in you need to whitelist the following domain
- opencerts.io (which is different to www.opencerts.io)
- mainnet.infura.io
- eth-mainnet.alchemyapi.io (fallback that we use if infura is down)

For the two last element, you also need to whitelist the ropsten domain, for verification over the ropsten network
