### ISSUE TITLE
Downloaded opencert file is not recognized by SkillPassport

### ISSUE THREAD

**Issue by lanlan3322** [OpenCerts/opencerts-website#609]
The downloaded opencert file has the format:
{
  **_"version": "https://schema.openattestation.com/2.0/schema.json",_**
  "data": {
    "id": "6496e699-2bdd-45ea-a1a7-dc79b54f89dc:string:CBC-02-20210227-00",
    "name": "d290a988-852d-4a4d-9d62-84d1deb2eb55:string:Certified Blockchain Consultant®",
    "description": "57577f1c-8b6f-4324-84f9-d8e88f1601c7:string:Certified Blockchain Consultant® issued by Institute of Blockchain®",
    "issuedOn": "d5ba9d4a-47d5-473a-836b-d6ef75351479:string:2021-02-27T00:00:00+08:00",
    "admissionDate": "923c5289-e520-4883-a695-d18a00ae3c94:string:2021-01-01T00:00:00+08:00",
    "graduationDate": "197e9009-be88-4a7b-8c96-1c0c3962f6d7:string:2021-02-27T00:00:00+08:00",
    "$template": {
...
...

The skillpassport page requires format to be:
{
  _**"schema": "opencerts/v2.0",**_
  "data": {
    "id": "6496e699-2bdd-45ea-a1a7-dc79b54f89dc:string:CBC-02-20210227-00",
    "name": "d290a988-852d-4a4d-9d62-84d1deb2eb55:string:Certified Blockchain Consultant®",
    "description": "57577f1c-8b6f-4324-84f9-d8e88f1601c7:string:Certified Blockchain Consultant® issued by Institute of Blockchain®",
    "issuedOn": "d5ba9d4a-47d5-473a-836b-d6ef75351479:string:2021-02-27T00:00:00+08:00",
    "admissionDate": "923c5289-e520-4883-a695-d18a00ae3c94:string:2021-01-01T00:00:00+08:00",
    "graduationDate": "197e9009-be88-4a7b-8c96-1c0c3962f6d7:string:2021-02-27T00:00:00+08:00",
    "$template": {

**Comment by Nebulis** [comment]
Which downloaded file ?

**Comment by lanlan3322** [comment]
Downloaded .opencerts file from opencerts.io

**Comment by Nebulis** [comment]
AFAICT we don't update the content of the file uploaded. So if the inputted file has `"version": "schema.openattestation.com/2.0/schema.json"`, then the downloaded file will have it as well
