### ISSUE TITLE
Migrate to OPenAttestation CLI tools

### ISSUE THREAD

**Issue by mohammedkalimullah** [OpenCerts/opencerts-website#651]
Hi,
we are in v2 but for batching the certificate, we use certificate CLI and we noticed that it has been deprecated. Do we need to switch to OpenAttestation CLI?
If we need to switch, what are steps to carry on. Please advice

**Comment by HJunyuan** [comment]
Hi there, the steps can be found in the readme here: https://github.com/OpenCerts/certificate-cli

> If you need to:
> - wrap/issue/obfuscate/ verify(cli) document, use https://github.com/Open-Attestation/open-attestation-cli
> - verify (programmatically) v2 document (only), use https://github.com/Open-Attestation/oa-verify
> - verify (programmatically) v1 and v2 documents, use https://github.com/OpenCerts/verify/
