### ISSUE TITLE
Opencert not display in bootstrap format

### ISSUE THREAD

**Issue by erwinsg** [OpenCerts/opencerts-website#665]
Hi @Nebulis, Team,

We have added 6 new templates in /src/templates, but when we tried to view Opencerts file, it displayed using default renderer.
![image](https://user-images.githubusercontent.com/43283667/155155914-d31d3ce8-10f3-4622-988a-d1dbe1d66b4d.png)

We deployed our templates using netlify account and created DNS sandbox OpenAttenstation for testing purpose.
Any step we missed out to configure?

**Comment by erwinsg** [comment]
Hi @Nebulis ,

We managed to solve opencert rendered using Default Renderer.

But now have different issue. It displayed not in bootstrap format.
![image](https://user-images.githubusercontent.com/43283667/155356107-9d59f08d-19eb-4e97-bbdd-7cce125fb01c.png)

**Comment by Nebulis** [comment]
Hello, just for info i left govtech and I'm not working on this project anymore

**Comment by simboonlong** [comment]
your renderer need to import bootstrap library via cdn or something. 

else, will be great if can share the repo then we can help take a look

**Comment by erwinsg** [comment]
Hi @simboonlong,

I managed to put in the bootstrap library in /static/index.html and its worked.
Maybe you can take a look whether our code is correct.

This is the repo
https://github.com/erwinsg/decentralized-renderer-react-template

**Comment by simboonlong** [comment]
looks about right
