### ISSUE TITLE
Update collaborator profile

### ISSUE THREAD

**Issue by wmclaxton** [OpenCerts/opencerts-website#675]
I want to update the description in this file. https://github.com/OpenCerts/opencerts-website/blob/master/src/components/Collaborate/collaborators.json

Please advise how to issue the PR.

**Comment by HJunyuan** [comment]
@wmclaxton Please make the request using [this form](https://go.gov.sg/opencerts-feedback) and include your company email and the new description. Thank you!

**Comment by wmclaxton** [comment]
I have done so, thanks.
