### ISSUE TITLE
Certificate is invalid, internal error

### ISSUE THREAD

**Issue by ygengygeng** [OpenCerts/opencerts-website#681]
Hi OpenCerts team,

I received the following error for a cert that was issued just today.

Whoops! It's not you, it's us
We encountered an internal error and cannot determine the cause, please try again later. If this issue persists, contact us using the feedback link below.

Here's the content of the file
[CERT22000123.txt](https://github.com/OpenCerts/opencerts-website/files/9157424/CERT22000123.txt)

Please assist to help us check. Thank you.

**Comment by HJunyuan** [comment]
Hi @ygengygeng, the file you provided here is an unwrapped raw document (i.e. not wrapped and not issued).

Do you have the issued document for us to have a look at?

**Comment by ygengygeng** [comment]
Sorry, I understand the issue now. I shall close the ticket.
