### ISSUE TITLE
DNS TXT Record and CNAME on Next Gen Firewall server setup

### ISSUE THREAD

**Issue by CITAcadAppsSupport** [OpenCerts/opencerts-website#724]
Hi,

Recently, we upgraded our server utilizing NexGen Firewall ELB, and as a result of this change, we are now forced to utilize cname on DNS.

Current setup, we had: (TXT Record) and (A Record)

new setup to replace (A Record) with (CNAME) due to next gen firewall ELB.

TXT and CNAME cannot coexist in this new setup.

Please do advise how to proceed from here.

Thank you.

**Comment by HJunyuan** [comment]
@CITAcadAppsSupport This is more of a DNS question rather than something related to OpenCerts.

In essence, a CNAME record simply points one subdomain (e.g. `sub.example.com`) to another domain (e.g. `main.example.com`).

As such, the TXT records should be published on `main.example.com`.

**Comment by CITAcadAppsSupport** [comment]
noted and thank you
