### ISSUE TITLE
Revocation message when verifying revoke via OCSP

### ISSUE THREAD

**Issue by ChenRen93** [OpenCerts/opencerts-website#735]
**Issues**
Hi, we are facing some issue regarding verification of certificate that has been revoked via OCSP. The current verifiable message display the revoked certificate as invalid instead of revoked.

**Reference**
![image](https://github.com/OpenCerts/opencerts-website/assets/17894339/2611bf73-7288-4d4d-b657-2af511a99db9)

**Comment by HJunyuan** [comment]
Hi @ChenRen93, could you try verifying the certificate in question using our [Toolkit (Verify)](https://toolkit.openattestation.com/verify)? Please share the output with us here. Thanks.

**Comment by ChenRen93** [comment]
Hi @HJunyuan, thanks for the fast respond. The fragment verification is shown correct but only the dropzone UI logic doesn't show it.

{
  "version": "https://schema.openattestation.com/2.0/schema.json",
  "data": {
    "id": "c9561183-5f79-42a7-bf53-b1dc1192231f:string:475450723",
    "name": "1b32b001-5254-4478-a89c-ac2d91486dfe:string:Certificate of Service",
    "issuedOn": "050fb039-5ec6-469a-8385-d2ce210ce197:string:2023-07-31T08:11:29.137298Z",
    "certificate": {
      "lastDateOfService": "56efbd03-d295-4387-be24-204cc454e449:string:2021/07/15"
    },
    "issuers": [
      {
        "id": "055c949a-ac70-48f3-87f1-831b8dba33fa:string:did:ethr:0x5a76bB903129F27F5B6dF3c4ee6e61B2cF2Af069",
        "name": "5027e39b-bc19-465b-b225-6449ef5c2f37:string:NHG",
        "identityProof": {
          "type": "d723a0d9-604a-4813-b0d9-e892725f2867:string:DNS-DID",
          "location": "ffbdcc99-b1a9-4c0a-9c25-f5b365657e3f:string:censored.accredify.dev",
          "key": "087e266e-b35b-46f7-8380-fcb5d4424285:string:did:ethr:0x5a76bB903129F27F5B6dF3c4ee6e61B2cF2Af069#controller"
        },
        "revocation": {
          "type": "7b343230-d781-4558-868a-1e355d629557:string:OCSP_RESPONDER",
          "location": "a2bbc117-f4b2-4deb-9930-e81e90f1cee1:string:https://censored.accredify.dev/revocation"
        }
      }
    ],
    "$template": {
      "name": "42f0829f-fa52-406f-b440-798dce58566f:string:COS-PACKAGE-2023-3",
      "type": "5da46f50-4344-4b73-aef1-a934d6e4c19d:string:EMBEDDED_RENDERER",
      "url": "8a8e1edf-a7ee-4d78-adea-a1e3f21dea98:string:https://renderer.censored.accredify.dev"
    },
    "recipient": {
      "name": "b67750f7-7cf2-4e4e-b3da-ab9bf670d9ef:string:EDWIN KOH",
      "nric": "0894f004-e0d0-4861-a8c8-9e4e98cde0f5:string:S9544873I",
      "rank": "aa13328b-089b-4e4e-a66b-f06cf49f57f6:string:PTE"
    },
    "transcript": {
      "service": {
        "type": "04278a4c-3ef8-49d5-8345-e952f26bd41e:string:Completed Full-time National Service",
        "releaseDate": "e1e465ac-d9f3-4469-a341-7c72ca68d24b:string:2023/07/11",
        "vocation": "71665670-e5fc-40ec-9172-31b607a17afc:string:PROGRAMMER",
        "rank": "4dbe4ee5-75af-4920-a046-1ec193a33b25:string:PTE",
        "status": {
          "type": "db1bc4a5-ef23-46a0-baad-c9634e4ac0c6:string:Completed Full-time National Service",
          "months": "58af56c6-88db-45eb-a9e8-57625a4f54dc:number:0",
          "years": "eeaa4ed3-be03-4f69-9685-5eb62ff9c31f:number:1"
        }
      },
      "assessment": {
        "conduct": "e16282df-d3ef-4289-89e6-d2a37b7052e3:string:Outstanding",
        "performance": "b064b86b-ee3e-411c-851d-f1ea29b44995:string:Outstanding"
      },
      "appraisal": "8da04b27-5b63-4571-ba33-1a53d9be8e3c:string:appraisal"
    }
  },
  "schema": "https://schemata.openattestation.com/com/openattestation/1.0/OpenAttestation.v3.json",
  "signature": {
    "type": "SHA3MerkleProof",
    "targetHash": "9684b5e9815806c9ed056f803fb4ab7987c77d028920cc5748a564737a04475a",
    "proof": [],
    "merkleRoot": "9684b5e9815806c9ed056f803fb4ab7987c77d028920cc5748a564737a04475a"
  },
  "proof": [
    {
      "type": "OpenAttestationSignature2018",
      "created": "2023-07-31T08:11:44.663Z",
      "proofPurpose": "assertionMethod",
      "verificationMethod": "did:ethr:0x5a76bB903129F27F5B6dF3c4ee6e61B2cF2Af069#controller",
      "signature": "0xf6036746eb2abbec95c3300aa0128b29fc7f8be5483b2a3f496100d0d72fad37509e15d3bacd982b9413e07d27f2aef39d5ca906b591810377174213cb2a76551b"
    }
  ]
}
Verify
Document is not valid:
Document integrity: true
Document status: false
Issuer identity: true
[
  {
    "type": "DOCUMENT_INTEGRITY",
    "name": "OpenAttestationHash",
    "data": true,
    "status": "VALID"
  },
  {
    "status": "SKIPPED",
    "type": "DOCUMENT_STATUS",
    "name": "OpenAttestationEthereumTokenRegistryStatus",
    "reason": {
      "code": 4,
      "codeString": "SKIPPED",
      "message": "Document issuers doesn't have \"tokenRegistry\" property or TOKEN_REGISTRY method"
    }
  },
  {
    "status": "SKIPPED",
    "type": "DOCUMENT_STATUS",
    "name": "OpenAttestationEthereumDocumentStoreStatus",
    "reason": {
      "code": 4,
      "codeString": "SKIPPED",
      "message": "Document issuers doesn't have \"documentStore\" or \"certificateStore\" property or DOCUMENT_STORE method"
    }
  },
  {
    "name": "OpenAttestationDidSignedDocumentStatus",
    "type": "DOCUMENT_STATUS",
    "data": {
      "issuedOnAll": true,
      "revokedOnAny": true,
      "details": {
        "issuance": [
          {
            "issued": true,
            "did": "did:ethr:0x5a76bB903129F27F5B6dF3c4ee6e61B2cF2Af069"
          }
        ],
        "revocation": [
          {
            "revoked": true,
            "address": "https://censored.accredify.dev/revocation",
            "reason": {
              "message": "Document 0x9684b5e9815806c9ed056f803fb4ab7987c77d028920cc5748a564737a04475a has been revoked under OCSP Responder: https://censored.accredify.dev/revocation",
              "code": 9,
              "codeString": "PRIVILEGE_WITHDRAWN"
            }
          }
        ]
      }
    },
    "status": "INVALID",
    "reason": {
      "message": "Document 0x9684b5e9815806c9ed056f803fb4ab7987c77d028920cc5748a564737a04475a has been revoked under OCSP Responder: https://censored.accredify.dev/revocation",
      "code": 9,
      "codeString": "PRIVILEGE_WITHDRAWN"
    }
  },
  {
    "status": "SKIPPED",
    "type": "ISSUER_IDENTITY",
    "name": "OpenAttestationDnsTxtIdentityProof",
    "reason": {
      "code": 2,
      "codeString": "SKIPPED",
      "message": "Document issuers doesn't have \"documentStore\" / \"tokenRegistry\" property or doesn't use DNS-TXT type"
    }
  },
  {
    "name": "OpenAttestationDnsDidIdentityProof",
    "type": "ISSUER_IDENTITY",
    "data": [
      {
        "location": "censored.accredify.dev",
        "key": "did:ethr:0x5a76bB903129F27F5B6dF3c4ee6e61B2cF2Af069#controller",
        "status": "VALID"
      }
    ],
    "status": "VALID"
  }
]

*We have censored the OCSP revocation route due to NDA*

**Comment by HJunyuan** [comment]
@ChenRen93 We have just issued a fix for this. You may test it again in about 15 mins time (buffer for deployment to complete)

**Comment by ChenRen93** [comment]
@HJunyuan  Thank you for the quick fixes, just tested it is working perfectly.
