### ISSUE TITLE
tabs at www.opencerts.io/viewer

### ISSUE THREAD

**Issue by CITAcadAppsSupport** [OpenCerts/opencerts-website#750]
Hi, currently Opencert has 3 tabs: https://www.opencerts.io/viewer
-Certificate
-Transcript
-Media

can we create tabs dynamically based on a json file?

thank you.

regards,

**Comment by HJunyuan** [comment]
Hi @CITAcadAppsSupport, the feature already exists as it is the renderer that defines these tabs.

Documentation: https://www.openattestation.com/docs/developer-section/quickstart/create-custom-renderer#certificate-of-completion-template-configuration
Example: https://github.com/OpenCerts/demo-opencerts-renderer/blob/22ca1f9fe674609073db54c652559f850adc0750/src/templates/govtech-demo-cert/index.tsx#L7-L21

**Comment by CITAcadAppsSupport** [comment]
Hi @HJunyuan 

thanks for the information.

regards,
