### ISSUE TITLE
Unable to start verification

### ISSUE THREAD

**Issue by waiaitch** [OpenCerts/opencerts-website#755]
Hello!

Was trying to verify a few files today but the OpenCerts website was not able to take in the files.
I have tried:
- Dragging and dropping the .opencert file onto the drag and drop component on the website
- Clicking on the 'Select File' button on the drag and drop component
- Using a Universal Actions link

Attached is a screenshot of some errors logged in the console when I opened it.
![image](https://github.com/OpenCerts/opencerts-website/assets/26197173/8eb2eebc-8bbf-4edf-a215-39e7c15236b4)

Please let me know if this is an issue on my end or if you require any additional information, thank you!

**Comment by zixiang2018** [comment]
Hi @waiaitch , thanks for raising the issue, we have just fixed it. You may try verifying the documents again.

**Comment by waiaitch** [comment]
Hi @zixiang2018, thanks for the speedy response!

I can verify that the drag & drop functionalities work now. However, I'm facing a different issue now where if the revocation type is defined as OCSP Responder with a revocation URL with a domain outside of these accepted ones:
![image](https://github.com/OpenCerts/opencerts-website/assets/26197173/a6f9fc3e-99ba-467a-999a-38fea4cf3e37)
We would face an error like this:
![image](https://github.com/OpenCerts/opencerts-website/assets/26197173/b52b862d-a48d-48a4-8043-2055c4b6b52e)

Is there any advice you can provide for how to continue with this if the OCSP responder is on a different domain? Please let me know if you require any additional information, thank you!

**Comment by zixiang2018** [comment]
Hi @waiaitch , any revocation URL should be able to work now. Do try it out again, thanks!

**Comment by waiaitch** [comment]
Hi @zixiang2018, can verify that it works now! Thank you so much for the prompt responses.
