### ISSUE TITLE
Did a pull request needed to be verified first before it is deployed to https://dev.opencerts.io/

### ISSUE THREAD

**Issue by erwinsg** [OpenCerts/opencerts-website#78]
hi Rui Jie, Raymond,

Did a pull request needed to be verified first before it is deployed to https://dev.opencerts.io/?

Please refer to my pull request using below hyperlink: 
https://github.com/OpenCerts/opencerts-website/pull/77

Thank you.

**Comment by rjchow** [comment]
yes it needs to be merged before you can view it on https://dev.opencerts.io

however you can view a preview by clicking the preview link inside the pull request, as mentioned before
