### ISSUE TITLE
npm installation failed in windows enviroment

### ISSUE THREAD

**Issue by argentra-kumar** [OpenCerts/opencerts-website#800]
Dear Team,

Here are the steps I've taken so far. I would appreciate your assistance in resolving the issue. Thank you.

1. Downloaded source code from master branch
2. Open project using visual studio code
3. Error encountered ,when run "npm install"

Error: 
npm warn cleanup     'D:\\temp\\ukissviewer\\opencerts-website\\node_modules\\core-js-pure',
npm warn cleanup     [Error: EBUSY: resource busy or locked, rmdir 'D:\temp\ukissviewer\opencerts-website\node_modules\core-js-pure'] {
npm warn cleanup       errno: -4082,
npm warn cleanup       code: 'EBUSY',
npm warn cleanup       syscall: 'rmdir',
npm warn cleanup       path: 'D:\\temp\\ukissviewer\\opencerts-website\\node_modules\\core-js-pure'
npm warn cleanup     }
npm warn cleanup   ],
npm warn cleanup   [
npm warn cleanup     'D:\\temp\\ukissviewer\\opencerts-website\\node_modules\\@govtechsg\\opencerts-verify\\node_modules\\@govtechsg\\open-attestation',
npm warn cleanup     [Error: EBUSY: resource busy or locked, rmdir 'D:\temp\ukissviewer\opencerts-website\node_modules\@govtechsg\opencerts-verify\node_modules\@govtechsg\open-attestation'] {
npm warn cleanup       errno: -4082,
npm warn cleanup       code: 'EBUSY',
npm warn cleanup       syscall: 'rmdir',
npm warn cleanup       path: 'D:\\temp\\ukissviewer\\opencerts-website\\node_modules\\@govtechsg\\opencerts-verify\\node_modules\\@govtechsg\\open-attestation'
npm warn cleanup     }
npm warn cleanup   ]
npm warn cleanup ]
npm error code 1
npm error path D:\temp\ukissviewer\opencerts-website\node_modules\@govtechsg\open-attestation
npm error command failed
npm error command C:\Windows\system32\cmd.exe /d /s /c node scripts/postInstall;
npm error node:internal/modules/cjs/loader:1143
npm error   throw err;
npm error   ^
npm error
npm error Error: Cannot find module 'D:\temp\ukissviewer\opencerts-website\node_modules\@govtechsg\open-attestation\scripts\postInstall;'
npm error     at Module._resolveFilename (node:internal/modules/cjs/loader:1140:15)
npm error     at Module._load (node:internal/modules/cjs/loader:981:27)
npm error     at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:128:12)
npm error     at node:internal/main/run_main_module:28:49 {
npm error   code: 'MODULE_NOT_FOUND',
npm error   requireStack: []
npm error }

**Comment by HJunyuan** [comment]
Hi @argentra-kumar, please get in touch with us by filling up this form: `https://go.gov.sg/opencerts-feedback`

Thank you!
