### ISSUE TITLE
Deploy SIT Template to production

### ISSUE THREAD

**Issue by erwinsg** [OpenCerts/opencerts-website#85]
Hi Rui Jie, Raymond,

SIT's (Singapore Institute of Technology) users have completed UAT and requested that the template is deployed to production.

I have sent you email on the UAT completion email.
Please advise. Thank you.

**Comment by rjchow** [comment]
It is already in production, just use the production store instead

**Comment by erwinsg** [comment]
Verification using this URL below, right?
https://opencerts.io/

**Comment by rjchow** [comment]
yes that is the url for production

In the future if you would like to contain your changes before pushing it to production, use the PR preview function - i.e don't merge the PR until you're done with all the UAT

**Comment by erwinsg** [comment]
Hi Rui Jie,

Do you mean that when I raise PR, I should mention to you to hold on to the merging?
I remember that I just created the PR and then you will approve the request and merge to UAT and Prod.

**Comment by rjchow** [comment]
Yup exactly, if there are still changes expected then the UAT should be carried out using the preview link

**Comment by erwinsg** [comment]
ok noted, Rui Jie.
Thanks so much for your support.

**Comment by rjchow** [comment]
no worries
